; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Dec 23 2021 06:43:57 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAEC7DWF3L5PB:
	dc.w DATAEC7DWF3L5PB_0-DATAEC7DWF3L5PB, DATAEC7DWF3L5PB_1-DATAEC7DWF3L5PB
	dc.w DATAEC7DWF3L5PB_2-DATAEC7DWF3L5PB
DATAEC7DWF3L5PB_0: dc.b $2
	dc.b $F0, $7, $0, $0, $F0
	dc.b $F0, $7, $8, $0, $0
DATAEC7DWF3L5PB_1: dc.b $2
	dc.b $F4, $6, $0, $8, $F4
	dc.b $F4, $2, $8, $8, $4
DATAEC7DWF3L5PB_2: dc.b $2
	dc.b $F0, $7, $0, $E, $F0
	dc.b $F0, $7, $8, $E, $0
	even