; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jan 16 2021 16:01:10 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAOVSFM3K93ER:
	dc.w DATAOVSFM3K93ER_0-DATAOVSFM3K93ER, DATAOVSFM3K93ER_1-DATAOVSFM3K93ER
	dc.w DATAOVSFM3K93ER_2-DATAOVSFM3K93ER, DATAOVSFM3K93ER_3-DATAOVSFM3K93ER
	dc.w DATAOVSFM3K93ER_4-DATAOVSFM3K93ER, DATAOVSFM3K93ER_5-DATAOVSFM3K93ER
DATAOVSFM3K93ER_0: dc.b $7
	dc.b $F6, $4, $20, $31, $E7
	dc.b $F4, $9, $0, $0, $E8
	dc.b $F4, $9, $0, $F, $0
	dc.b $4, $8, $0, $15, $E8
	dc.b $4, $4, $0, $18, $0
	dc.b $F1, $8, $0, $1A, $EC
	dc.b $F1, $4, $0, $1D, $4
DATAOVSFM3K93ER_1: dc.b $7
	dc.b $F6, $4, $20, $31, $E7
	dc.b $F4, $9, $0, $0, $E8
	dc.b $F4, $9, $0, $F, $0
	dc.b $4, $8, $0, $15, $E8
	dc.b $4, $4, $0, $18, $0
	dc.b $F4, $8, $0, $1F, $EC
	dc.b $F4, $4, $0, $22, $4
DATAOVSFM3K93ER_2: dc.b $8
	dc.b $F6, $4, $20, $31, $E7
	dc.b $4, $0, $0, $30, $C
	dc.b $F4, $9, $0, $0, $E8
	dc.b $F4, $9, $0, $F, $0
	dc.b $4, $8, $0, $15, $E8
	dc.b $4, $4, $0, $18, $0
	dc.b $F1, $8, $0, $1A, $EC
	dc.b $F1, $4, $0, $1D, $4
DATAOVSFM3K93ER_3: dc.b $9
	dc.b $F6, $4, $20, $31, $E7
	dc.b $4, $0, $0, $30, $C
	dc.b $F4, $9, $0, $0, $E8
	dc.b $F4, $9, $0, $F, $0
	dc.b $4, $8, $0, $15, $E8
	dc.b $4, $4, $0, $18, $0
	dc.b $F4, $8, $0, $1F, $EC
	dc.b $F4, $4, $0, $22, $4
	dc.b $4, $0, $0, $30, $F
DATAOVSFM3K93ER_4: dc.b $7
	dc.b $F6, $4, $20, $31, $EB
	dc.b $F4, $D, $0, $0, $EC
	dc.b $4, $C, $0, $8, $EC
	dc.b $4, $0, $0, $C, $C
	dc.b $C, $4, $0, $D, $F4
	dc.b $F1, $4, $20, $1D, $4
	dc.b $F1, $8, $0, $1A, $EC
DATAOVSFM3K93ER_5: dc.b $5
	dc.b $F6, $4, $20, $31, $EB
	dc.b $F4, $D, $0, $0, $EC
	dc.b $4, $C, $0, $8, $EC
	dc.b $4, $0, $0, $C, $C
	dc.b $C, $4, $0, $D, $F4
	even