; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jun 23 2021 22:53:21 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA75B3EPD7DND:
	dc.w DATA75B3EPD7DND_0-DATA75B3EPD7DND, DATA75B3EPD7DND_1-DATA75B3EPD7DND
	dc.w DATA75B3EPD7DND_2-DATA75B3EPD7DND, DATA75B3EPD7DND_3-DATA75B3EPD7DND
DATA75B3EPD7DND_0: dc.b $3
	dc.b $0, $D, $0, $5, $F0
	dc.b $F0, $5, $0, $0, $F8
	dc.b $F8, $0, $0, $4, $8
DATA75B3EPD7DND_1: dc.b $2
	dc.b $F0, $D, $0, $D, $F0
	dc.b $0, $D, $0, $15, $F0
DATA75B3EPD7DND_2: dc.b $3
	dc.b $F0, $D, $0, $1D, $F0
	dc.b $0, $9, $0, $25, $F8
	dc.b $0, $0, $0, $2B, $F0
DATA75B3EPD7DND_3: dc.b $3
	dc.b $F0, $9, $0, $2C, $F8
	dc.b $0, $D, $0, $32, $F0
	dc.b $F0, $1, $0, $3A, $F0
	even