; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Mar 17 2021 02:15:26 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAECA7YYLABQ:
	dc.w DATAECA7YYLABQ_0-DATAECA7YYLABQ, DATAECA7YYLABQ_1-DATAECA7YYLABQ
	dc.w DATAECA7YYLABQ_2-DATAECA7YYLABQ, DATAECA7YYLABQ_3-DATAECA7YYLABQ
DATAECA7YYLABQ_0: dc.b $2
	dc.b $F8, $D, $0, $2, $CC
	dc.b $F8, $9, $0, $A, $EC
DATAECA7YYLABQ_1: dc.b $2
	dc.b $F8, $D, $0, $10, $5
	dc.b $F8, $5, $0, $18, $25
DATAECA7YYLABQ_2: dc.b $2
	dc.b $F8, $9, $0, $1C, $C4
	dc.b $F8, $D, $0, $8, $DC
DATAECA7YYLABQ_3: dc.b $2
	dc.b $F8, $D, $0, $14, $C
	dc.b $F8, $D, $0, $C, $2C
	even