; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jul 20 2022 12:07:18 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5LLGPQCJKXX:
	dc.w DATA5LLGPQCJKXX_0-DATA5LLGPQCJKXX, DATA5LLGPQCJKXX_1-DATA5LLGPQCJKXX
	dc.w DATA5LLGPQCJKXX_2-DATA5LLGPQCJKXX, DATA5LLGPQCJKXX_3-DATA5LLGPQCJKXX
DATA5LLGPQCJKXX_0: dc.b $2
	dc.b $F8, $D, $0, $2, $CC
	dc.b $F8, $9, $0, $A, $EC
DATA5LLGPQCJKXX_1: dc.b $2
	dc.b $F8, $D, $0, $10, $5
	dc.b $F8, $5, $0, $18, $25
DATA5LLGPQCJKXX_2: dc.b $2
	dc.b $F8, $9, $0, $1C, $CF
	dc.b $F8, $9, $0, $A, $E7
DATA5LLGPQCJKXX_3: dc.b $2
	dc.b $F8, $D, $0, $10, $0
	dc.b $F8, $5, $0, $18, $20
	even