; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jul 17 2021 22:57:44 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA9MEX53FH1I7:
	dc.w DATA9MEX53FH1I7_0-DATA9MEX53FH1I7
DATA9MEX53FH1I7_0: dc.b $8
	dc.b $E8, $F, $0, $0, $D0
	dc.b $8, $E, $0, $10, $D0
	dc.b $E0, $4, $0, $1C, $E8
	dc.b $E8, $F, $0, $1E, $F0
	dc.b $8, $E, $0, $2E, $F0
	dc.b $E8, $F, $0, $3A, $10
	dc.b $8, $E, $0, $4A, $10
	dc.b $D8, $9, $0, $56, $18
	even