; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Mar 30 2022 10:45:02 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATALAB6YJ5E8NS:
	dc.w DATALAB6YJ5E8NS_0-DATALAB6YJ5E8NS
DATALAB6YJ5E8NS_0: dc.b $7
	dc.b $E0, $B, $60, $0, $10
	dc.b $0, $B, $0, $C, $10
	dc.b $0, $F, $0, $18, $F0
	dc.b $0, $B, $0, $28, $D8
	dc.b $E8, $E, $0, $34, $F0
	dc.b $E8, $6, $0, $40, $E0
	dc.b $F0, $1, $0, $46, $D8
	even