; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Nov 24 2021 12:07:37 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA16C11TRNJ3U:
	dc.w DATA16C11TRNJ3U_0-DATA16C11TRNJ3U
DATA16C11TRNJ3U_0: dc.b $2
	dc.b $EC, $7, $0, $0, $F8
	dc.b $C, $4, $0, $8, $F8
	even