; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 04 2021 22:51:18 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAS9SR0CTUMR:
	dc.w DATAS9SR0CTUMR_0-DATAS9SR0CTUMR
DATAS9SR0CTUMR_0: dc.b $D
	dc.b $F6, $0, $0, $51, $C
	dc.b $10, $D, $0, $0, $D4
	dc.b $10, $D, $0, $8, $F4
	dc.b $10, $9, $0, $10, $14
	dc.b $0, $D, $60, $26, $D4
	dc.b $0, $D, $60, $2E, $F4
	dc.b $0, $9, $60, $36, $14
	dc.b $F0, $D, $0, $3C, $D4
	dc.b $F0, $9, $0, $44, $F4
	dc.b $E8, $C, $0, $4A, $DF
	dc.b $E8, $4, $0, $4E, $FF
	dc.b $E5, $0, $0, $50, $F0
	dc.b $E0, $F, $60, $16, $C
	even