; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu May 20 2021 16:51:43 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATABF0IG74RRR:
	dc.w DATABF0IG74RRR_0-DATABF0IG74RRR, DATABF0IG74RRR_1-DATABF0IG74RRR
	dc.w DATABF0IG74RRR_2-DATABF0IG74RRR, DATABF0IG74RRR_3-DATABF0IG74RRR
	dc.w DATABF0IG74RRR_4-DATABF0IG74RRR, DATABF0IG74RRR_5-DATABF0IG74RRR
	dc.w DATABF0IG74RRR_6-DATABF0IG74RRR, DATABF0IG74RRR_7-DATABF0IG74RRR
	dc.w DATABF0IG74RRR_8-DATABF0IG74RRR
DATABF0IG74RRR_0: dc.b $8
	dc.b $F8, $5, $0, $3E, $B8
	dc.b $F8, $5, $0, $32, $C8
	dc.b $F8, $5, $0, $2E, $D8
	dc.b $F8, $1, $0, $20, $E8
	dc.b $F8, $5, $0, $8, $F0
	dc.b $F8, $5, $0, $1C, $10
	dc.b $F8, $5, $0, $0, $20
	dc.b $F8, $5, $0, $3E, $30
DATABF0IG74RRR_1: dc.b $6
	dc.b $F8, $5, $0, $36, $D0
	dc.b $F8, $5, $0, $0, $E0
	dc.b $F8, $5, $0, $3E, $F0
	dc.b $F8, $5, $0, $3E, $0
	dc.b $F8, $5, $0, $10, $10
	dc.b $F8, $5, $0, $C, $20
DATABF0IG74RRR_2: dc.b $8
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $4A, $F9
	dc.b $F8, $9, $1, $64, $18
	dc.b $F8, $D, $1, $6A, $30
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $0, $57, $AA
	dc.b $F8, $1, $0, $5F, $CA
DATABF0IG74RRR_3: dc.b $7
	dc.b $F8, $D, $21, $5A, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F0, $28
	dc.b $F8, $1, $1, $70, $48
DATABF0IG74RRR_4: dc.b $7
	dc.b $F8, $D, $21, $52, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F8, $28
	dc.b $F8, $1, $1, $70, $48
DATABF0IG74RRR_5: dc.b $0
DATABF0IG74RRR_6: dc.b $0
DATABF0IG74RRR_7: dc.b $0
DATABF0IG74RRR_8: dc.b $0
	even