; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jun 05 2021 10:49:27 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAFTMOVHHPR0N:
	dc.w DATAFTMOVHHPR0N_0-DATAFTMOVHHPR0N, DATAFTMOVHHPR0N_1-DATAFTMOVHHPR0N
	dc.w DATAFTMOVHHPR0N_2-DATAFTMOVHHPR0N, DATAFTMOVHHPR0N_3-DATAFTMOVHHPR0N
	dc.w DATAFTMOVHHPR0N_4-DATAFTMOVHHPR0N, DATAFTMOVHHPR0N_5-DATAFTMOVHHPR0N
	dc.w DATAFTMOVHHPR0N_6-DATAFTMOVHHPR0N, DATAFTMOVHHPR0N_7-DATAFTMOVHHPR0N
	dc.w DATAFTMOVHHPR0N_8-DATAFTMOVHHPR0N
DATAFTMOVHHPR0N_0: dc.b $8
	dc.b $F8, $5, $0, $3E, $B8
	dc.b $F8, $5, $0, $32, $C8
	dc.b $F8, $5, $0, $2E, $D8
	dc.b $F8, $1, $0, $20, $E8
	dc.b $F8, $5, $0, $8, $F0
	dc.b $F8, $5, $0, $1C, $10
	dc.b $F8, $5, $0, $0, $20
	dc.b $F8, $5, $0, $3E, $30
DATAFTMOVHHPR0N_1: dc.b $6
	dc.b $F8, $5, $0, $36, $D0
	dc.b $F8, $5, $0, $0, $E0
	dc.b $F8, $5, $0, $3E, $F0
	dc.b $F8, $5, $0, $3E, $0
	dc.b $F8, $5, $0, $10, $10
	dc.b $F8, $5, $0, $C, $20
DATAFTMOVHHPR0N_2: dc.b $8
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $50, $F9
	dc.b $F8, $9, $1, $6A, $18
	dc.b $F8, $D, $1, $70, $30
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $0, $57, $AA
	dc.b $F8, $1, $0, $5F, $CA
DATAFTMOVHHPR0N_3: dc.b $7
	dc.b $F8, $D, $21, $60, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $50, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F6, $28
	dc.b $F8, $1, $1, $76, $48
DATAFTMOVHHPR0N_4: dc.b $7
	dc.b $F8, $D, $21, $58, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $50, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $FE, $28
	dc.b $F8, $1, $1, $76, $48
DATAFTMOVHHPR0N_5: dc.b $0
DATAFTMOVHHPR0N_6: dc.b $0
DATAFTMOVHHPR0N_7: dc.b $0
DATAFTMOVHHPR0N_8: dc.b $0
	even