; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Dec 27 2021 09:43:06 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAJZTU3H8KUVB:
	dc.w DATAJZTU3H8KUVB_0-DATAJZTU3H8KUVB, DATAJZTU3H8KUVB_1-DATAJZTU3H8KUVB
	dc.w DATAJZTU3H8KUVB_2-DATAJZTU3H8KUVB, DATAJZTU3H8KUVB_3-DATAJZTU3H8KUVB
	dc.w DATAJZTU3H8KUVB_4-DATAJZTU3H8KUVB, DATAJZTU3H8KUVB_5-DATAJZTU3H8KUVB
	dc.w DATAJZTU3H8KUVB_6-DATAJZTU3H8KUVB, DATAJZTU3H8KUVB_7-DATAJZTU3H8KUVB
	dc.w DATAJZTU3H8KUVB_8-DATAJZTU3H8KUVB
DATAJZTU3H8KUVB_0: dc.b $8
	dc.b $F8, $5, $0, $3E, $B8
	dc.b $F8, $5, $0, $32, $C8
	dc.b $F8, $5, $0, $2E, $D8
	dc.b $F8, $1, $0, $20, $E8
	dc.b $F8, $5, $0, $8, $F0
	dc.b $F8, $5, $0, $1C, $10
	dc.b $F8, $5, $0, $0, $20
	dc.b $F8, $5, $0, $3E, $30
DATAJZTU3H8KUVB_1: dc.b $A
	dc.b $F8, $5, $0, $36, $9C
	dc.b $F8, $5, $0, $0, $AC
	dc.b $F8, $5, $0, $3E, $BC
	dc.b $F8, $5, $0, $3E, $CC
	dc.b $F8, $5, $0, $10, $DC
	dc.b $F8, $5, $0, $C, $EC
	dc.b $F8, $5, $0, $0, $C
	dc.b $F8, $5, $0, $8, $1C
	dc.b $F8, $5, $0, $42, $2C
	dc.b $0, $0, $0, $52, $3C
DATAJZTU3H8KUVB_2: dc.b $6
	dc.b $F8, $D, $21, $4A, $B0
	dc.b $F8, $1, $21, $62, $D0
	dc.b $F8, $9, $1, $64, $18
	dc.b $F8, $D, $1, $6A, $30
	dc.b $F7, $4, $0, $6E, $CD
	dc.b $FF, $4, $18, $6E, $CD
DATAJZTU3H8KUVB_3: dc.b $7
	dc.b $F8, $D, $21, $5A, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F0, $28
	dc.b $F8, $1, $1, $70, $48
DATAJZTU3H8KUVB_4: dc.b $7
	dc.b $F8, $D, $21, $52, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F8, $28
	dc.b $F8, $1, $1, $70, $48
DATAJZTU3H8KUVB_5: dc.b $0
DATAJZTU3H8KUVB_6: dc.b $1
	dc.b $F2, $5, $0, $70, $20
DATAJZTU3H8KUVB_7: dc.b $1
	dc.b $F2, $5, $0, $74, $20
DATAJZTU3H8KUVB_8: dc.b $1
	dc.b $F2, $5, $0, $78, $20
	even