; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Sep 28 2021 18:43:22 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAB3CNQWLH1VG:
	dc.w $0, DATAB3CNQWLH1VG_1-DATAB3CNQWLH1VG
	dc.w DATAB3CNQWLH1VG_2-DATAB3CNQWLH1VG, DATAB3CNQWLH1VG_3-DATAB3CNQWLH1VG
DATAB3CNQWLH1VG_1: dc.b $3
	dc.b $F8, $5, $0, $0, $F8
	dc.b $F3, $5, $0, $0, $FC
	dc.b $F5, $5, $0, $0, $F4
DATAB3CNQWLH1VG_2: dc.b $2
	dc.b $F8, $5, $0, $0, $F8
	dc.b $F3, $5, $0, $0, $FC
DATAB3CNQWLH1VG_3: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
	even