; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jan 02 2021 04:27:56 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATACN6X7TKSPYK:
	dc.w DATACN6X7TKSPYK_0-DATACN6X7TKSPYK, DATACN6X7TKSPYK_1-DATACN6X7TKSPYK
	dc.w DATACN6X7TKSPYK_2-DATACN6X7TKSPYK, DATACN6X7TKSPYK_3-DATACN6X7TKSPYK
DATACN6X7TKSPYK_0: dc.b $9
	dc.b $80, $D, $A0, $0, $0
	dc.b $80, $D, $A0, $18, $20
	dc.b $80, $D, $A0, $20, $40
	dc.b $90, $D, $A0, $10, $0
	dc.b $90, $D, $A0, $28, $28
	dc.b $A0, $D, $A0, $8, $0
	dc.b $A0, $9, $A0, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
DATACN6X7TKSPYK_1: dc.b $9
	dc.b $80, $D, $A0, $0, $0
	dc.b $80, $D, $A0, $18, $20
	dc.b $80, $D, $A0, $20, $40
	dc.b $90, $D, $A0, $10, $0
	dc.b $90, $D, $A0, $28, $28
	dc.b $A0, $D, $80, $8, $0
	dc.b $A0, $9, $A0, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
DATACN6X7TKSPYK_2: dc.b $9
	dc.b $80, $D, $A0, $0, $0
	dc.b $80, $D, $A0, $18, $20
	dc.b $80, $D, $A0, $20, $40
	dc.b $90, $D, $80, $10, $0
	dc.b $90, $D, $A0, $28, $28
	dc.b $A0, $D, $A0, $8, $0
	dc.b $A0, $9, $A0, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
DATACN6X7TKSPYK_3: dc.b $9
	dc.b $80, $D, $A0, $0, $0
	dc.b $80, $D, $A0, $18, $20
	dc.b $80, $D, $A0, $20, $40
	dc.b $90, $D, $80, $10, $0
	dc.b $90, $D, $A0, $28, $28
	dc.b $A0, $D, $80, $8, $0
	dc.b $A0, $9, $A0, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
	even