; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 04 2021 00:28:43 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAYREX44C6C7P:
	dc.w DATAYREX44C6C7P_0-DATAYREX44C6C7P, DATAYREX44C6C7P_1-DATAYREX44C6C7P
	dc.w DATAYREX44C6C7P_2-DATAYREX44C6C7P, DATAYREX44C6C7P_3-DATAYREX44C6C7P
DATAYREX44C6C7P_0: dc.b $2
	dc.b $F4, $B, $0, $0, $F4
	dc.b $EC, $8, $0, $C, $F4
DATAYREX44C6C7P_1: dc.b $2
	dc.b $F4, $F, $0, $F, $F0
	dc.b $EC, $C, $0, $1F, $F0
DATAYREX44C6C7P_2: dc.b $0
DATAYREX44C6C7P_3: dc.b $1
	dc.b $F1, $F, $0, $23, $F3
	even