; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Sep 26 2021 23:50:45 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA8O6HNLEURP:
	dc.w DATA8O6HNLEURP_0-DATA8O6HNLEURP, DATA8O6HNLEURP_1-DATA8O6HNLEURP
	dc.w DATA8O6HNLEURP_2-DATA8O6HNLEURP, DATA8O6HNLEURP_3-DATA8O6HNLEURP
DATA8O6HNLEURP_0: dc.b $2
	dc.b $F4, $B, $0, $0, $F4
	dc.b $EC, $8, $0, $C, $F4
DATA8O6HNLEURP_1: dc.b $2
	dc.b $F4, $F, $0, $F, $F5
	dc.b $EC, $C, $0, $1F, $F5
DATA8O6HNLEURP_2: dc.b $3
	dc.b $F9, $C, $0, $33, $EC
	dc.b $F1, $8, $0, $37, $F4
	dc.b $1, $A, $0, $3A, $F4
DATA8O6HNLEURP_3: dc.b $1
	dc.b $F1, $F, $0, $23, $F3
	even