; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jan 16 2021 02:21:46 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATALF075XSCCR:
	dc.w DATALF075XSCCR_0-DATALF075XSCCR, DATALF075XSCCR_1-DATALF075XSCCR
	dc.w DATALF075XSCCR_2-DATALF075XSCCR, DATALF075XSCCR_3-DATALF075XSCCR
DATALF075XSCCR_0: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $C, $0, $10, $F0
DATALF075XSCCR_1: dc.b $2
	dc.b $F4, $F, $0, $14, $F0
	dc.b $EC, $C, $0, $24, $F0
DATALF075XSCCR_2: dc.b $2
	dc.b $F8, $F, $0, $28, $F0
	dc.b $F0, $C, $0, $38, $F0
DATALF075XSCCR_3: dc.b $1
	dc.b $EC, $F, $0, $3C, $F0
	even