; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu May 27 2021 20:36:28 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAEXCOV4G3JLL:
	dc.w DATAEXCOV4G3JLL_0-DATAEXCOV4G3JLL, DATAEXCOV4G3JLL_1-DATAEXCOV4G3JLL
	dc.w DATAEXCOV4G3JLL_2-DATAEXCOV4G3JLL, DATAEXCOV4G3JLL_3-DATAEXCOV4G3JLL
	dc.w DATAEXCOV4G3JLL_4-DATAEXCOV4G3JLL, DATAEXCOV4G3JLL_5-DATAEXCOV4G3JLL
	dc.w DATAEXCOV4G3JLL_6-DATAEXCOV4G3JLL, DATAEXCOV4G3JLL_7-DATAEXCOV4G3JLL
DATAEXCOV4G3JLL_0: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATAEXCOV4G3JLL_1: dc.b $1
	dc.b $F8, $5, $0, $4, $F8
DATAEXCOV4G3JLL_2: dc.b $1
	dc.b $F8, $1, $0, $8, $FC
DATAEXCOV4G3JLL_3: dc.b $1
	dc.b $F8, $5, $8, $4, $F8
DATAEXCOV4G3JLL_4: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
DATAEXCOV4G3JLL_5: dc.b $1
	dc.b $F8, $5, $18, $A, $F8
DATAEXCOV4G3JLL_6: dc.b $1
	dc.b $F8, $5, $8, $A, $F8
DATAEXCOV4G3JLL_7: dc.b $1
	dc.b $F8, $5, $10, $A, $F8
	even