; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed May 05 2021 14:04:12 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5J5W2C056S5:
	dc.w DATA5J5W2C056S5_0-DATA5J5W2C056S5, DATA5J5W2C056S5_1-DATA5J5W2C056S5
	dc.w DATA5J5W2C056S5_2-DATA5J5W2C056S5, DATA5J5W2C056S5_3-DATA5J5W2C056S5
DATA5J5W2C056S5_0: dc.b $6
	dc.b $E4, $1, $0, $0, $F8
	dc.b $E4, $1, $8, $0, $0
	dc.b $F4, $3, $20, $2, $F8
	dc.b $F4, $3, $28, $2, $0
	dc.b $D4, $1, $0, $6, $F8
	dc.b $D4, $1, $8, $6, $0
DATA5J5W2C056S5_1: dc.b $4
	dc.b $E4, $1, $0, $0, $F8
	dc.b $E4, $1, $8, $0, $0
	dc.b $F4, $3, $20, $2, $F8
	dc.b $F4, $3, $28, $2, $0
DATA5J5W2C056S5_2: dc.b $2
	dc.b $F8, $1, $0, $6, $F8
	dc.b $F8, $1, $8, $6, $0
DATA5J5W2C056S5_3: dc.b $6
	dc.b $E4, $1, $0, $0, $F8
	dc.b $E4, $1, $8, $0, $0
	dc.b $F4, $3, $20, $2, $F8
	dc.b $F4, $3, $28, $2, $0
	dc.b $D4, $1, $0, $8, $F8
	dc.b $D4, $1, $8, $8, $0
	even