; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu May 20 2021 16:40:23 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAHW4YG9ONB04:
	dc.w DATAHW4YG9ONB04_0-DATAHW4YG9ONB04, DATAHW4YG9ONB04_1-DATAHW4YG9ONB04
	dc.w DATAHW4YG9ONB04_2-DATAHW4YG9ONB04, DATAHW4YG9ONB04_3-DATAHW4YG9ONB04
	dc.w DATAHW4YG9ONB04_4-DATAHW4YG9ONB04, DATAHW4YG9ONB04_5-DATAHW4YG9ONB04
	dc.w DATAHW4YG9ONB04_6-DATAHW4YG9ONB04, DATAHW4YG9ONB04_7-DATAHW4YG9ONB04
	dc.w DATAHW4YG9ONB04_8-DATAHW4YG9ONB04, DATAHW4YG9ONB04_9-DATAHW4YG9ONB04
	dc.w DATAHW4YG9ONB04_A-DATAHW4YG9ONB04, DATAHW4YG9ONB04_B-DATAHW4YG9ONB04
DATAHW4YG9ONB04_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_2: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_3: dc.b $2
	dc.b $F5, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_4: dc.b $2
	dc.b $F5, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_5: dc.b $2
	dc.b $F5, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_6: dc.b $2
	dc.b $F5, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_7: dc.b $2
	dc.b $F5, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_8: dc.b $2
	dc.b $F5, $5, $0, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_9: dc.b $2
	dc.b $F5, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_A: dc.b $2
	dc.b $F5, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHW4YG9ONB04_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
	even