; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Jul 13 2021 20:54:14 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAS227BC26TL:
	dc.w DATAS227BC26TL_0-DATAS227BC26TL, DATAS227BC26TL_1-DATAS227BC26TL
	dc.w DATAS227BC26TL_2-DATAS227BC26TL, DATAS227BC26TL_3-DATAS227BC26TL
	dc.w DATAS227BC26TL_4-DATAS227BC26TL, DATAS227BC26TL_5-DATAS227BC26TL
	dc.w DATAS227BC26TL_6-DATAS227BC26TL, DATAS227BC26TL_7-DATAS227BC26TL
	dc.w DATAS227BC26TL_8-DATAS227BC26TL, DATAS227BC26TL_9-DATAS227BC26TL
	dc.w DATAS227BC26TL_A-DATAS227BC26TL, DATAS227BC26TL_B-DATAS227BC26TL
	dc.w DATAS227BC26TL_C-DATAS227BC26TL
DATAS227BC26TL_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_2: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_3: dc.b $2
	dc.b $F5, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_4: dc.b $2
	dc.b $F5, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_5: dc.b $2
	dc.b $F5, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_6: dc.b $2
	dc.b $F5, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_7: dc.b $2
	dc.b $F5, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_8: dc.b $2
	dc.b $F5, $5, $0, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_9: dc.b $2
	dc.b $F5, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_A: dc.b $2
	dc.b $F5, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAS227BC26TL_B: dc.b $2
	dc.b $F1, $0, $0, $44, $FF
	dc.b $FF, $D, $0, $38, $F0
DATAS227BC26TL_C: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
	even