; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jul 11 2022 12:45:13 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAR4LIFQK4OIJ:
	dc.w DATAR4LIFQK4OIJ_0-DATAR4LIFQK4OIJ, DATAR4LIFQK4OIJ_1-DATAR4LIFQK4OIJ
	dc.w DATAR4LIFQK4OIJ_2-DATAR4LIFQK4OIJ, DATAR4LIFQK4OIJ_3-DATAR4LIFQK4OIJ
	dc.w DATAR4LIFQK4OIJ_4-DATAR4LIFQK4OIJ, DATAR4LIFQK4OIJ_5-DATAR4LIFQK4OIJ
	dc.w DATAR4LIFQK4OIJ_6-DATAR4LIFQK4OIJ, DATAR4LIFQK4OIJ_7-DATAR4LIFQK4OIJ
	dc.w DATAR4LIFQK4OIJ_8-DATAR4LIFQK4OIJ, DATAR4LIFQK4OIJ_9-DATAR4LIFQK4OIJ
	dc.w DATAR4LIFQK4OIJ_A-DATAR4LIFQK4OIJ, DATAR4LIFQK4OIJ_B-DATAR4LIFQK4OIJ
	dc.w DATAR4LIFQK4OIJ_C-DATAR4LIFQK4OIJ
DATAR4LIFQK4OIJ_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_2: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_3: dc.b $2
	dc.b $F5, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_4: dc.b $2
	dc.b $F5, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_5: dc.b $2
	dc.b $F5, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_6: dc.b $2
	dc.b $F5, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_7: dc.b $2
	dc.b $F5, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_8: dc.b $2
	dc.b $F5, $5, $0, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_9: dc.b $2
	dc.b $F5, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_A: dc.b $2
	dc.b $F5, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAR4LIFQK4OIJ_B: dc.b $2
	dc.b $4, $0, $0, $44, $FC
	dc.b $FF, $D, $0, $38, $F0
DATAR4LIFQK4OIJ_C: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
	even