; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Jan 21 2021 03:29:03 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA9YQ60XETCIW:
	dc.w DATA9YQ60XETCIW_0-DATA9YQ60XETCIW, DATA9YQ60XETCIW_1-DATA9YQ60XETCIW
	dc.w DATA9YQ60XETCIW_2-DATA9YQ60XETCIW, DATA9YQ60XETCIW_3-DATA9YQ60XETCIW
	dc.w DATA9YQ60XETCIW_4-DATA9YQ60XETCIW, DATA9YQ60XETCIW_5-DATA9YQ60XETCIW
	dc.w DATA9YQ60XETCIW_6-DATA9YQ60XETCIW
DATA9YQ60XETCIW_0: dc.b $4
	dc.b $F0, $D, $0, $0, $EC
	dc.b $0, $C, $0, $8, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $8, $0, $E, $F4
DATA9YQ60XETCIW_1: dc.b $4
	dc.b $F1, $D, $0, $0, $EC
	dc.b $1, $C, $0, $8, $EC
	dc.b $F9, $1, $0, $C, $C
	dc.b $9, $8, $0, $11, $F4
DATA9YQ60XETCIW_2: dc.b $5
	dc.b $F0, $D, $0, $0, $EC
	dc.b $0, $C, $0, $14, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $4, $0, $18, $EC
	dc.b $8, $4, $0, $12, $FC
DATA9YQ60XETCIW_3: dc.b $1
	dc.b $FA, $0, $0, $1A, $10
DATA9YQ60XETCIW_4: dc.b $1
	dc.b $FA, $0, $0, $1B, $10
DATA9YQ60XETCIW_5: dc.b $1
	dc.b $FA, $0, $0, $1C, $10
DATA9YQ60XETCIW_6: dc.b $0
	even