; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jun 09 2021 20:27:54 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATASLVYKQV1DH:
	dc.w $0, DATASLVYKQV1DH_1-DATASLVYKQV1DH
	dc.w DATASLVYKQV1DH_2-DATASLVYKQV1DH, $0
DATASLVYKQV1DH_1: dc.b $7
	dc.b $0, $8, $0, $EC, $1
	dc.b $0, $0, $0, $EF, $19
	dc.b $0, $0, $0, $EF, $21
	dc.b $0, $C, $0, $F0, $31
	dc.b $0, $0, $0, $F4, $51
	dc.b $0, $8, $0, $F5, $61
	dc.b $0, $8, $0, $F7, $79
DATASLVYKQV1DH_2: dc.b $1E
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	even