; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jul 31 2021 12:49:42 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA0SF2J1PUU0KI:
	dc.w $0, DATA0SF2J1PUU0KI_1-DATA0SF2J1PUU0KI
	dc.w DATA0SF2J1PUU0KI_2-DATA0SF2J1PUU0KI, $0
DATA0SF2J1PUU0KI_1: dc.b $1
	dc.b $0, $C, $0, $C3, $1
DATA0SF2J1PUU0KI_2: dc.b $1E
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	even