; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Dec 29 2020 08:40:21 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATADAZ8EK47M7T:
	dc.w DATADAZ8EK47M7T_0-DATADAZ8EK47M7T, DATADAZ8EK47M7T_1-DATADAZ8EK47M7T
	dc.w DATADAZ8EK47M7T_2-DATADAZ8EK47M7T, DATADAZ8EK47M7T_3-DATADAZ8EK47M7T
	dc.w DATADAZ8EK47M7T_4-DATADAZ8EK47M7T, DATADAZ8EK47M7T_5-DATADAZ8EK47M7T
	dc.w DATADAZ8EK47M7T_6-DATADAZ8EK47M7T
DATADAZ8EK47M7T_0: dc.b $7
	dc.b $E0, $C, $20, $0, $F0
	dc.b $E8, $D, $20, $4, $E0
	dc.b $E8, $D, $20, $C, $0
	dc.b $F8, $E, $20, $14, $E0
	dc.b $F8, $E, $20, $20, $0
	dc.b $10, $D, $20, $2C, $E0
	dc.b $10, $D, $20, $34, $0
DATADAZ8EK47M7T_1: dc.b $1
	dc.b $F8, $9, $0, $3C, $F4
DATADAZ8EK47M7T_2: dc.b $6
	dc.b $0, $8, $20, $42, $E0
	dc.b $8, $C, $20, $45, $E0
	dc.b $0, $4, $20, $49, $10
	dc.b $8, $C, $20, $4B, $0
	dc.b $10, $D, $20, $2C, $E0
	dc.b $10, $D, $20, $34, $0
DATADAZ8EK47M7T_3: dc.b $1
	dc.b $F8, $9, $0, $4F, $F4
DATADAZ8EK47M7T_4: dc.b $2
	dc.b $E8, $E, $20, $55, $F0
	dc.b $0, $E, $20, $61, $F0
DATADAZ8EK47M7T_5: dc.b $1
	dc.b $F0, $7, $20, $6D, $F8
DATADAZ8EK47M7T_6: dc.b $0
	even