; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Aug 07 2021 15:35:45 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAETIJ2ZDQYHS:
	dc.w DATAETIJ2ZDQYHS_0-DATAETIJ2ZDQYHS
DATAETIJ2ZDQYHS_0: dc.b $2
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $0, $C, $0
	even