; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Sep 25 2021 23:27:46 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAK1220FT6DO9:
	dc.w DATAK1220FT6DO9_0-DATAK1220FT6DO9, DATAK1220FT6DO9_1-DATAK1220FT6DO9
	dc.w DATAK1220FT6DO9_2-DATAK1220FT6DO9
DATAK1220FT6DO9_0: dc.b $C
	dc.b $C8, $F, $0, $0, $DC
	dc.b $C0, $F, $0, $10, $FC
	dc.b $C0, $0, $0, $20, $1C
	dc.b $E8, $D, $0, $21, $DC
	dc.b $F8, $0, $20, $39, $FC
	dc.b $E0, $B, $0, $29, $FC
	dc.b $D8, $2, $0, $35, $1C
	dc.b $F8, $0, $0, $38, $EC
	dc.b $0, $1, $20, $39, $FC
	dc.b $10, $1, $20, $39, $FC
	dc.b $20, $1, $20, $39, $FC
	dc.b $30, $1, $20, $39, $FC
DATAK1220FT6DO9_1: dc.b $B
	dc.b $E8, $C, $A3, $52, $F4
	dc.b $E8, $0, $A3, $56, $14
	dc.b $F0, $C, $A3, $57, $EC
	dc.b $F0, $4, $A3, $5B, $C
	dc.b $F8, $D, $A3, $5E, $E4
	dc.b $F8, $D, $A3, $66, $4
	dc.b $8, $D, $A3, $6E, $DC
	dc.b $8, $D, $A3, $76, $FC
	dc.b $8, $1, $A3, $7E, $1C
	dc.b $F0, $0, $A3, $5D, $E4
	dc.b $0, $0, $A3, $5D, $DC
DATAK1220FT6DO9_2: dc.b $B
	dc.b $F3, $C, $60, $0, $FD
	dc.b $F3, $0, $60, $4, $1D
	dc.b $FB, $C, $60, $5, $F5
	dc.b $3, $D, $60, $C, $ED
	dc.b $3, $D, $60, $14, $D
	dc.b $13, $D, $60, $1C, $E5
	dc.b $13, $D, $60, $24, $5
	dc.b $13, $1, $60, $2C, $25
	dc.b $FB, $4, $60, $9, $15
	dc.b $B, $0, $60, $B, $E5
	dc.b $FB, $0, $60, $B, $ED
	even