; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Aug 23 2021 23:16:27 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATADVH31WOQABG:
	dc.w DATADVH31WOQABG_0-DATADVH31WOQABG, DATADVH31WOQABG_1-DATADVH31WOQABG
DATADVH31WOQABG_0: dc.b $B
	dc.b $C8, $F, $0, $0, $DC
	dc.b $C0, $F, $0, $10, $FC
	dc.b $C0, $0, $0, $20, $1C
	dc.b $E8, $D, $0, $21, $DC
	dc.b $E0, $B, $0, $29, $FC
	dc.b $D8, $2, $0, $35, $1C
	dc.b $F8, $0, $0, $38, $EC
	dc.b $0, $1, $0, $39, $FC
	dc.b $10, $1, $0, $39, $FC
	dc.b $20, $1, $0, $39, $FC
	dc.b $30, $1, $0, $39, $FC
DATADVH31WOQABG_1: dc.b $9
	dc.b $E8, $C, $43, $52, $F4
	dc.b $E8, $0, $43, $56, $14
	dc.b $F0, $C, $43, $57, $EC
	dc.b $F0, $8, $43, $5B, $C
	dc.b $F8, $D, $43, $5E, $E4
	dc.b $F8, $D, $43, $66, $4
	dc.b $8, $D, $43, $6E, $DC
	dc.b $8, $D, $43, $76, $FC
	dc.b $8, $1, $43, $7E, $1C
	even