; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue May 10 2022 17:56:03 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAZ5UXKKY8BZ:
	dc.w DATAZ5UXKKY8BZ_0-DATAZ5UXKKY8BZ, DATAZ5UXKKY8BZ_1-DATAZ5UXKKY8BZ
	dc.w DATAZ5UXKKY8BZ_2-DATAZ5UXKKY8BZ, DATAZ5UXKKY8BZ_3-DATAZ5UXKKY8BZ
	dc.w DATAZ5UXKKY8BZ_4-DATAZ5UXKKY8BZ, DATAZ5UXKKY8BZ_5-DATAZ5UXKKY8BZ
	dc.w DATAZ5UXKKY8BZ_6-DATAZ5UXKKY8BZ, DATAZ5UXKKY8BZ_7-DATAZ5UXKKY8BZ
DATAZ5UXKKY8BZ_0: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATAZ5UXKKY8BZ_1: dc.b $1
	dc.b $F8, $5, $0, $4, $F8
DATAZ5UXKKY8BZ_2: dc.b $1
	dc.b $F8, $1, $0, $8, $FC
DATAZ5UXKKY8BZ_3: dc.b $1
	dc.b $F8, $5, $8, $4, $F8
DATAZ5UXKKY8BZ_4: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
DATAZ5UXKKY8BZ_5: dc.b $1
	dc.b $F8, $5, $18, $A, $F8
DATAZ5UXKKY8BZ_6: dc.b $1
	dc.b $F8, $5, $8, $A, $F7
DATAZ5UXKKY8BZ_7: dc.b $1
	dc.b $F8, $5, $10, $A, $F7
	even