; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 04 2021 02:41:02 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAJ959JM56V07:
	dc.w DATAJ959JM56V07_0-DATAJ959JM56V07, DATAJ959JM56V07_1-DATAJ959JM56V07
	dc.w DATAJ959JM56V07_2-DATAJ959JM56V07, DATAJ959JM56V07_3-DATAJ959JM56V07
	dc.w DATAJ959JM56V07_4-DATAJ959JM56V07, DATAJ959JM56V07_5-DATAJ959JM56V07
	dc.w DATAJ959JM56V07_6-DATAJ959JM56V07, DATAJ959JM56V07_7-DATAJ959JM56V07
DATAJ959JM56V07_0: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATAJ959JM56V07_1: dc.b $1
	dc.b $F8, $5, $0, $4, $F8
DATAJ959JM56V07_2: dc.b $1
	dc.b $F8, $1, $0, $8, $FC
DATAJ959JM56V07_3: dc.b $1
	dc.b $F8, $5, $8, $4, $F8
DATAJ959JM56V07_4: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
DATAJ959JM56V07_5: dc.b $1
	dc.b $F8, $5, $18, $A, $F8
DATAJ959JM56V07_6: dc.b $1
	dc.b $F8, $5, $8, $A, $F7
DATAJ959JM56V07_7: dc.b $1
	dc.b $F8, $5, $10, $A, $F7
	even