; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Jul 18 2021 02:24:28 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5PRHCDVPUC5:
	dc.w DATA5PRHCDVPUC5_0-DATA5PRHCDVPUC5, DATA5PRHCDVPUC5_1-DATA5PRHCDVPUC5
	dc.w DATA5PRHCDVPUC5_2-DATA5PRHCDVPUC5, DATA5PRHCDVPUC5_3-DATA5PRHCDVPUC5
	dc.w DATA5PRHCDVPUC5_4-DATA5PRHCDVPUC5, DATA5PRHCDVPUC5_5-DATA5PRHCDVPUC5
	dc.w DATA5PRHCDVPUC5_6-DATA5PRHCDVPUC5, DATA5PRHCDVPUC5_7-DATA5PRHCDVPUC5
DATA5PRHCDVPUC5_0: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATA5PRHCDVPUC5_1: dc.b $1
	dc.b $F8, $5, $0, $4, $F8
DATA5PRHCDVPUC5_2: dc.b $1
	dc.b $F8, $1, $0, $8, $FC
DATA5PRHCDVPUC5_3: dc.b $1
	dc.b $F8, $5, $8, $4, $F8
DATA5PRHCDVPUC5_4: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
DATA5PRHCDVPUC5_5: dc.b $1
	dc.b $F8, $5, $18, $A, $F8
DATA5PRHCDVPUC5_6: dc.b $1
	dc.b $F8, $5, $8, $A, $F7
DATA5PRHCDVPUC5_7: dc.b $1
	dc.b $F8, $5, $10, $A, $F7
	even