; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Mar 20 2022 14:47:33 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATADGIHW9PJU6V:
	dc.w DATADGIHW9PJU6V_0-DATADGIHW9PJU6V, DATADGIHW9PJU6V_1-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_2-DATADGIHW9PJU6V, DATADGIHW9PJU6V_3-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_4-DATADGIHW9PJU6V, DATADGIHW9PJU6V_5-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_6-DATADGIHW9PJU6V, DATADGIHW9PJU6V_7-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_8-DATADGIHW9PJU6V, DATADGIHW9PJU6V_9-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_A-DATADGIHW9PJU6V, DATADGIHW9PJU6V_B-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_C-DATADGIHW9PJU6V, DATADGIHW9PJU6V_D-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_E-DATADGIHW9PJU6V, DATADGIHW9PJU6V_F-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_10-DATADGIHW9PJU6V, DATADGIHW9PJU6V_11-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_12-DATADGIHW9PJU6V, DATADGIHW9PJU6V_13-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_14-DATADGIHW9PJU6V, DATADGIHW9PJU6V_15-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_16-DATADGIHW9PJU6V, DATADGIHW9PJU6V_17-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_18-DATADGIHW9PJU6V, DATADGIHW9PJU6V_19-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_1A-DATADGIHW9PJU6V, DATADGIHW9PJU6V_1B-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_1C-DATADGIHW9PJU6V, DATADGIHW9PJU6V_1D-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_1E-DATADGIHW9PJU6V, DATADGIHW9PJU6V_1F-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_20-DATADGIHW9PJU6V, DATADGIHW9PJU6V_21-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_22-DATADGIHW9PJU6V, DATADGIHW9PJU6V_23-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_24-DATADGIHW9PJU6V, DATADGIHW9PJU6V_25-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_26-DATADGIHW9PJU6V, DATADGIHW9PJU6V_27-DATADGIHW9PJU6V
	dc.w DATADGIHW9PJU6V_28-DATADGIHW9PJU6V
DATADGIHW9PJU6V_0: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_1: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_2: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_3: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_4: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_5: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_6: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_7: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_8: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_9: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_A: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_B: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_C: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_D: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_E: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_F: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_10: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_11: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_12: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_13: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_14: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_15: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_16: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_17: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_18: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_19: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_1A: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_1B: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_1C: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_1D: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_1E: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_1F: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_20: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_21: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_22: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_23: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_24: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_25: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATADGIHW9PJU6V_26: dc.b $1
	dc.b $F3, $7, $0, $12, $F8
DATADGIHW9PJU6V_27: dc.b $1
	dc.b $FB, $A, $0, $12, $F0
DATADGIHW9PJU6V_28: dc.b $1
	dc.b $3, $D, $0, $12, $E8
	even