; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Mar 20 2022 01:52:47 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAM9R0LEMPN7:
	dc.w DATAM9R0LEMPN7_0-DATAM9R0LEMPN7, DATAM9R0LEMPN7_1-DATAM9R0LEMPN7
	dc.w DATAM9R0LEMPN7_2-DATAM9R0LEMPN7
DATAM9R0LEMPN7_0: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $EC, $1, $0, $C, $4
	dc.b $F4, $0, $0, $E, $C
	dc.b $C, $8, $0, $F, $F4
DATAM9R0LEMPN7_1: dc.b $1
	dc.b $EF, $7, $0, $12, $F9
DATAM9R0LEMPN7_2: dc.b $1
	dc.b $2, $D, $0, $12, $F0
	even