; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue May 24 2022 16:25:39 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAV6KMFDB741:
	dc.w $0, DATAV6KMFDB741_1-DATAV6KMFDB741
	dc.w DATAV6KMFDB741_2-DATAV6KMFDB741, DATAV6KMFDB741_3-DATAV6KMFDB741
	dc.w DATAV6KMFDB741_4-DATAV6KMFDB741, DATAV6KMFDB741_5-DATAV6KMFDB741
	dc.w DATAV6KMFDB741_6-DATAV6KMFDB741, DATAV6KMFDB741_7-DATAV6KMFDB741
	dc.w DATAV6KMFDB741_8-DATAV6KMFDB741
DATAV6KMFDB741_1: dc.b $6
	dc.b $E8, $4, $0, $0, $F8
	dc.b $F0, $4, $18, $0, $F8
	dc.b $8, $0, $0, $2, $F8
	dc.b $8, $0, $8, $2, $0
	dc.b $10, $0, $10, $2, $F8
	dc.b $10, $0, $18, $2, $0
DATAV6KMFDB741_2: dc.b $6
	dc.b $EC, $4, $0, $0, $EC
	dc.b $F4, $4, $18, $0, $EC
	dc.b $4, $0, $0, $2, $4
	dc.b $4, $0, $8, $2, $C
	dc.b $C, $0, $10, $2, $4
	dc.b $C, $0, $18, $2, $C
DATAV6KMFDB741_3: dc.b $6
	dc.b $F8, $4, $0, $0, $E8
	dc.b $0, $4, $18, $0, $E8
	dc.b $F8, $0, $0, $2, $8
	dc.b $F8, $0, $8, $2, $10
	dc.b $0, $0, $10, $2, $8
	dc.b $0, $0, $18, $2, $10
DATAV6KMFDB741_4: dc.b $6
	dc.b $4, $4, $0, $0, $EC
	dc.b $C, $4, $18, $0, $EC
	dc.b $EC, $0, $0, $2, $4
	dc.b $EC, $0, $8, $2, $C
	dc.b $F4, $0, $10, $2, $4
	dc.b $F4, $0, $18, $2, $C
DATAV6KMFDB741_5: dc.b $6
	dc.b $8, $4, $8, $0, $F8
	dc.b $10, $4, $10, $0, $F8
	dc.b $E8, $0, $0, $2, $F8
	dc.b $E8, $0, $8, $2, $0
	dc.b $F0, $0, $10, $2, $F8
	dc.b $F0, $0, $18, $2, $0
DATAV6KMFDB741_6: dc.b $6
	dc.b $4, $4, $8, $0, $4
	dc.b $C, $4, $10, $0, $4
	dc.b $EC, $0, $0, $2, $EC
	dc.b $EC, $0, $8, $2, $F4
	dc.b $F4, $0, $10, $2, $EC
	dc.b $F4, $0, $18, $2, $F4
DATAV6KMFDB741_7: dc.b $6
	dc.b $F8, $4, $8, $0, $8
	dc.b $0, $4, $10, $0, $8
	dc.b $F8, $0, $0, $2, $E8
	dc.b $F8, $0, $8, $2, $F0
	dc.b $0, $0, $10, $2, $E8
	dc.b $0, $0, $18, $2, $F0
DATAV6KMFDB741_8: dc.b $6
	dc.b $EC, $4, $8, $0, $4
	dc.b $F4, $4, $10, $0, $4
	dc.b $4, $0, $0, $2, $EC
	dc.b $4, $0, $8, $2, $F4
	dc.b $C, $0, $10, $2, $EC
	dc.b $C, $0, $18, $2, $F4
	even