; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Nov 10 2021 02:50:10 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA43OL4VXR9GD:
	dc.w $0, DATA43OL4VXR9GD_1-DATA43OL4VXR9GD
	dc.w DATA43OL4VXR9GD_2-DATA43OL4VXR9GD, DATA43OL4VXR9GD_3-DATA43OL4VXR9GD
	dc.w DATA43OL4VXR9GD_4-DATA43OL4VXR9GD, DATA43OL4VXR9GD_5-DATA43OL4VXR9GD
	dc.w DATA43OL4VXR9GD_6-DATA43OL4VXR9GD, DATA43OL4VXR9GD_7-DATA43OL4VXR9GD
	dc.w DATA43OL4VXR9GD_8-DATA43OL4VXR9GD
DATA43OL4VXR9GD_1: dc.b $3
	dc.b $FE, $0, $0, $22, $F
	dc.b $F4, $0, $0, $24, $E
	dc.b $ED, $0, $0, $26, $5
DATA43OL4VXR9GD_2: dc.b $3
	dc.b $E9, $0, $0, $26, $FB
	dc.b $ED, $0, $0, $24, $5
	dc.b $F5, $0, $0, $25, $D
DATA43OL4VXR9GD_3: dc.b $3
	dc.b $F0, $0, $0, $26, $F0
	dc.b $E9, $0, $0, $24, $FB
	dc.b $EE, $0, $0, $25, $4
DATA43OL4VXR9GD_4: dc.b $3
	dc.b $E9, $0, $0, $22, $F9
	dc.b $F0, $0, $0, $24, $F0
	dc.b $FD, $0, $0, $26, $E9
DATA43OL4VXR9GD_5: dc.b $3
	dc.b $F0, $0, $0, $22, $EE
	dc.b $FD, $0, $0, $24, $E9
	dc.b $FE, $0, $0, $26, $11
DATA43OL4VXR9GD_6: dc.b $3
	dc.b $FD, $0, $0, $22, $E7
	dc.b $FE, $0, $0, $24, $11
	dc.b $F4, $0, $0, $26, $E
DATA43OL4VXR9GD_7: dc.b $8
	dc.b $E8, $0, $0, $39, $FC
	dc.b $EE, $0, $0, $39, $A
	dc.b $FC, $0, $0, $39, $10
	dc.b $A, $0, $0, $39, $A
	dc.b $10, $0, $0, $39, $FC
	dc.b $A, $0, $0, $39, $EE
	dc.b $FC, $0, $0, $39, $E8
	dc.b $EE, $0, $0, $39, $EE
DATA43OL4VXR9GD_8: dc.b $8
	dc.b $EC, $0, $0, $24, $F6
	dc.b $F6, $0, $0, $24, $EC
	dc.b $2, $0, $0, $24, $EC
	dc.b $EC, $0, $0, $24, $2
	dc.b $F6, $0, $0, $24, $C
	dc.b $2, $0, $0, $24, $C
	dc.b $C, $0, $0, $24, $2
	dc.b $C, $0, $0, $24, $F6
	even