; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Jan 15 2021 01:21:34 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATARTKOU3C84U:
	dc.w $0, DATARTKOU3C84U_1-DATARTKOU3C84U
	dc.w DATARTKOU3C84U_2-DATARTKOU3C84U, DATARTKOU3C84U_3-DATARTKOU3C84U
	dc.w DATARTKOU3C84U_4-DATARTKOU3C84U, DATARTKOU3C84U_5-DATARTKOU3C84U
	dc.w DATARTKOU3C84U_6-DATARTKOU3C84U, DATARTKOU3C84U_7-DATARTKOU3C84U
	dc.w DATARTKOU3C84U_8-DATARTKOU3C84U
DATARTKOU3C84U_1: dc.b $3
	dc.b $FE, $0, $0, $22, $F
	dc.b $F4, $0, $0, $24, $E
	dc.b $ED, $0, $0, $26, $5
DATARTKOU3C84U_2: dc.b $3
	dc.b $E9, $0, $0, $26, $FB
	dc.b $ED, $0, $0, $24, $5
	dc.b $F5, $0, $0, $25, $D
DATARTKOU3C84U_3: dc.b $3
	dc.b $F0, $0, $0, $26, $F0
	dc.b $E9, $0, $0, $24, $FB
	dc.b $EE, $0, $0, $25, $4
DATARTKOU3C84U_4: dc.b $3
	dc.b $E9, $0, $0, $22, $F9
	dc.b $F0, $0, $0, $24, $F0
	dc.b $FD, $0, $0, $26, $E9
DATARTKOU3C84U_5: dc.b $3
	dc.b $F0, $0, $0, $22, $EE
	dc.b $FD, $0, $0, $24, $E9
	dc.b $FE, $0, $0, $26, $11
DATARTKOU3C84U_6: dc.b $3
	dc.b $FD, $0, $0, $22, $E7
	dc.b $FE, $0, $0, $24, $11
	dc.b $F4, $0, $0, $26, $E
DATARTKOU3C84U_7: dc.b $8
	dc.b $E8, $0, $0, $26, $FD
	dc.b $EF, $0, $0, $26, $F2
	dc.b $FA, $0, $0, $26, $E9
	dc.b $F0, $0, $0, $26, $8
	dc.b $FB, $0, $0, $26, $10
	dc.b $6, $0, $0, $26, $9
	dc.b $F, $0, $0, $26, $FD
	dc.b $5, $0, $0, $26, $F2
DATARTKOU3C84U_8: dc.b $8
	dc.b $E9, $0, $0, $26, $F8
	dc.b $F2, $0, $0, $26, $EE
	dc.b $FE, $0, $0, $26, $EC
	dc.b $E9, $0, $0, $26, $5
	dc.b $F3, $0, $0, $26, $E
	dc.b $4, $0, $0, $26, $F
	dc.b $F, $0, $0, $26, $4
	dc.b $C, $0, $0, $26, $F5
	even