; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Sep 26 2021 22:07:03 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAGZ8P5Z900TI:
	dc.w DATAGZ8P5Z900TI_0-DATAGZ8P5Z900TI, DATAGZ8P5Z900TI_1-DATAGZ8P5Z900TI
	dc.w DATAGZ8P5Z900TI_2-DATAGZ8P5Z900TI, DATAGZ8P5Z900TI_3-DATAGZ8P5Z900TI
	dc.w DATAGZ8P5Z900TI_4-DATAGZ8P5Z900TI
DATAGZ8P5Z900TI_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
DATAGZ8P5Z900TI_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
DATAGZ8P5Z900TI_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
DATAGZ8P5Z900TI_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
DATAGZ8P5Z900TI_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even