; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Sep 26 2021 22:09:04 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATARS36JHN5JRH:
	dc.w DATARS36JHN5JRH_0-DATARS36JHN5JRH, DATARS36JHN5JRH_1-DATARS36JHN5JRH
	dc.w DATARS36JHN5JRH_2-DATARS36JHN5JRH, DATARS36JHN5JRH_3-DATARS36JHN5JRH
	dc.w DATARS36JHN5JRH_4-DATARS36JHN5JRH
DATARS36JHN5JRH_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
DATARS36JHN5JRH_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
DATARS36JHN5JRH_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
DATARS36JHN5JRH_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
DATARS36JHN5JRH_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even