; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jun 05 2021 11:02:58 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATACNJKW3D82BR:
	dc.w DATACNJKW3D82BR_0-DATACNJKW3D82BR, DATACNJKW3D82BR_1-DATACNJKW3D82BR
	dc.w DATACNJKW3D82BR_2-DATACNJKW3D82BR, DATACNJKW3D82BR_3-DATACNJKW3D82BR
	dc.w DATACNJKW3D82BR_4-DATACNJKW3D82BR
DATACNJKW3D82BR_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
DATACNJKW3D82BR_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
DATACNJKW3D82BR_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
DATACNJKW3D82BR_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
DATACNJKW3D82BR_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even