; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Oct 10 2021 01:08:13 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAJU8UJA9V4EL:
	dc.w $0, DATAJU8UJA9V4EL_1-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_2-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_3-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_4-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_5-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_6-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_7-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_8-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_9-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_A-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_B-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_C-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_D-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_E-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_F-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_10-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_11-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_12-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_13-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_14-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_15-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_16-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_17-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_18-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_19-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_1A-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_1B-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_1C-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_1D-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_1E-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_1F-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_20-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_21-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_22-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_23-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_24-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_25-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_26-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_27-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_28-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_29-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_2A-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_2B-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_2C-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_2D-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_2E-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_2F-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_30-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_31-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_32-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_33-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_34-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_35-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_36-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_37-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_38-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_39-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_3A-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_3B-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_3C-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_3D-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_3E-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_3F-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_40-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_41-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_42-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_43-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_44-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_45-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_46-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_47-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_48-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_49-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_4A-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_4B-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_4C-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_4D-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_4E-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_4F-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_50-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_51-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_52-DATAJU8UJA9V4EL, DATAJU8UJA9V4EL_53-DATAJU8UJA9V4EL
	dc.w DATAJU8UJA9V4EL_54-DATAJU8UJA9V4EL
DATAJU8UJA9V4EL_1: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATAJU8UJA9V4EL_2: dc.b $4
	dc.b $EB, $D, $0, $0, $EB
	dc.b $FB, $9, $0, $8, $EB
	dc.b $FB, $6, $0, $E, $3
	dc.b $B, $4, $0, $14, $EB
DATAJU8UJA9V4EL_3: dc.b $2
	dc.b $EC, $D, $0, $0, $EB
	dc.b $FC, $E, $0, $8, $F3
DATAJU8UJA9V4EL_4: dc.b $2
	dc.b $FD, $A, $0, $0, $F4
	dc.b $ED, $9, $0, $9, $F4
DATAJU8UJA9V4EL_5: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATAJU8UJA9V4EL_6: dc.b $2
	dc.b $FC, $E, $0, $0, $EC
	dc.b $EC, $9, $0, $C, $F4
DATAJU8UJA9V4EL_7: dc.b $3
	dc.b $ED, $D, $0, $0, $EB
	dc.b $FD, $C, $0, $8, $F3
	dc.b $5, $9, $0, $C, $F3
DATAJU8UJA9V4EL_8: dc.b $5
	dc.b $EC, $9, $0, $0, $EA
	dc.b $EC, $6, $0, $6, $2
	dc.b $FC, $8, $0, $C, $EA
	dc.b $4, $9, $0, $F, $F2
	dc.b $14, $0, $0, $15, $FA
DATAJU8UJA9V4EL_9: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATAJU8UJA9V4EL_A: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATAJU8UJA9V4EL_B: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATAJU8UJA9V4EL_C: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATAJU8UJA9V4EL_D: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATAJU8UJA9V4EL_E: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATAJU8UJA9V4EL_F: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATAJU8UJA9V4EL_10: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATAJU8UJA9V4EL_11: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $FC, $4, $0, $6, $FB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $4, $9, $0, $E, $FB
DATAJU8UJA9V4EL_12: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAJU8UJA9V4EL_13: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $F4, $A, $0, $8, $FD
	dc.b $EC, $0, $0, $11, $FD
DATAJU8UJA9V4EL_14: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $D, $0, $0, $6, $FB
	dc.b $F5, $A, $0, $7, $FB
	dc.b $FD, $0, $0, $10, $13
	dc.b $F5, $4, $0, $11, $EB
	dc.b $ED, $4, $0, $13, $F3
DATAJU8UJA9V4EL_15: dc.b $6
	dc.b $FB, $6, $0, $0, $EB
	dc.b $B, $0, $0, $6, $FB
	dc.b $F3, $A, $0, $7, $FB
	dc.b $F3, $4, $0, $10, $EB
	dc.b $EB, $4, $0, $12, $FB
	dc.b $E3, $8, $0, $14, $F3
DATAJU8UJA9V4EL_16: dc.b $4
	dc.b $FA, $6, $0, $0, $EC
	dc.b $2, $4, $0, $6, $FC
	dc.b $EA, $A, $0, $8, $FC
	dc.b $F2, $4, $0, $11, $EC
DATAJU8UJA9V4EL_17: dc.b $5
	dc.b $FB, $6, $0, $0, $EB
	dc.b $3, $8, $0, $6, $FB
	dc.b $F3, $D, $0, $9, $FB
	dc.b $F3, $4, $0, $11, $EB
	dc.b $EB, $8, $0, $13, $F3
DATAJU8UJA9V4EL_18: dc.b $4
	dc.b $ED, $A, $0, $0, $FA
	dc.b $5, $4, $0, $9, $FA
	dc.b $FD, $6, $0, $B, $EA
	dc.b $F5, $4, $0, $11, $EA
DATAJU8UJA9V4EL_19: dc.b $5
	dc.b $EC, $A, $0, $0, $FC
	dc.b $4, $4, $0, $9, $FC
	dc.b $C, $0, $0, $B, $FC
	dc.b $FC, $6, $0, $C, $EC
	dc.b $F4, $4, $0, $12, $EC
DATAJU8UJA9V4EL_1A: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAJU8UJA9V4EL_1B: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAJU8UJA9V4EL_1C: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAJU8UJA9V4EL_1D: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAJU8UJA9V4EL_1E: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $0, $0, $8, $EE
	dc.b $FE, $E, $0, $9, $F6
DATAJU8UJA9V4EL_1F: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAJU8UJA9V4EL_20: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $0, $0, $8, $EE
	dc.b $FE, $E, $0, $9, $F6
DATAJU8UJA9V4EL_21: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAJU8UJA9V4EL_22: dc.b $2
	dc.b $EF, $7, $0, $0, $F2
	dc.b $F7, $B, $0, $8, $2
DATAJU8UJA9V4EL_23: dc.b $2
	dc.b $F4, $6, $0, $0, $EF
	dc.b $F4, $B, $0, $6, $FF
DATAJU8UJA9V4EL_24: dc.b $2
	dc.b $F3, $F, $0, $0, $F2
	dc.b $FB, $2, $0, $10, $12
DATAJU8UJA9V4EL_25: dc.b $2
	dc.b $F4, $6, $0, $0, $EF
	dc.b $F4, $B, $0, $6, $FF
DATAJU8UJA9V4EL_26: dc.b $3
	dc.b $F2, $7, $0, $0, $EE
	dc.b $A, $0, $0, $8, $FE
	dc.b $EA, $B, $0, $9, $FE
DATAJU8UJA9V4EL_27: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAJU8UJA9V4EL_28: dc.b $3
	dc.b $F2, $7, $0, $0, $EE
	dc.b $A, $0, $0, $8, $FE
	dc.b $EA, $B, $0, $9, $FE
DATAJU8UJA9V4EL_29: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAJU8UJA9V4EL_2A: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJU8UJA9V4EL_2B: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJU8UJA9V4EL_2C: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJU8UJA9V4EL_2D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJU8UJA9V4EL_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJU8UJA9V4EL_2F: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATAJU8UJA9V4EL_30: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATAJU8UJA9V4EL_31: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $F7, $1, $0, $C, $C
	dc.b $7, $C, $0, $E, $F4
	dc.b $EF, $0, $0, $12, $C
DATAJU8UJA9V4EL_32: dc.b $4
	dc.b $EB, $9, $8, $0, $F4
	dc.b $FB, $9, $8, $6, $FC
	dc.b $FB, $6, $8, $C, $EC
	dc.b $B, $4, $8, $12, $4
DATAJU8UJA9V4EL_33: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATAJU8UJA9V4EL_34: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $8, $0, $C, $F4
DATAJU8UJA9V4EL_35: dc.b $5
	dc.b $0, $C, $0, $0, $EC
	dc.b $8, $5, $0, $4, $F4
	dc.b $8, $0, $0, $8, $4
	dc.b $E8, $A, $0, $9, $F4
	dc.b $F0, $1, $0, $12, $C
DATAJU8UJA9V4EL_36: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $C, $0, $B, $EC
	dc.b $8, $5, $0, $F, $F4
	dc.b $8, $0, $0, $13, $4
DATAJU8UJA9V4EL_37: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
	dc.b $10, $4, $0, $F, $F4
DATAJU8UJA9V4EL_38: dc.b $3
	dc.b $8, $8, $0, $0, $F4
	dc.b $10, $4, $0, $3, $F4
	dc.b $E8, $B, $0, $5, $F4
DATAJU8UJA9V4EL_39: dc.b $2
	dc.b $E8, $B, $0, $0, $F3
	dc.b $8, $8, $0, $C, $F3
DATAJU8UJA9V4EL_3A: dc.b $2
	dc.b $E8, $F, $0, $0, $F3
	dc.b $8, $8, $0, $10, $F3
DATAJU8UJA9V4EL_3B: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATAJU8UJA9V4EL_3C: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATAJU8UJA9V4EL_3D: dc.b $3
	dc.b $FC, $D, $0, $0, $F2
	dc.b $EC, $9, $0, $8, $F2
	dc.b $C, $4, $0, $E, $2
DATAJU8UJA9V4EL_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAJU8UJA9V4EL_3F: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAJU8UJA9V4EL_40: dc.b $3
	dc.b $F4, $D, $8, $0, $EC
	dc.b $FC, $5, $8, $8, $C
	dc.b $4, $8, $8, $C, $F4
DATAJU8UJA9V4EL_41: dc.b $3
	dc.b $F4, $D, $0, $0, $EC
	dc.b $FC, $0, $0, $8, $C
	dc.b $4, $C, $0, $9, $F4
DATAJU8UJA9V4EL_42: dc.b $3
	dc.b $F4, $D, $8, $0, $F4
	dc.b $FC, $0, $8, $8, $EC
	dc.b $4, $C, $8, $9, $EC
DATAJU8UJA9V4EL_43: dc.b $8
	dc.b $E8, $1, $0, $0, $C
	dc.b $10, $0, $0, $2, $F4
	dc.b $8, $8, $0, $3, $F4
	dc.b $10, $0, $0, $6, $FC
	dc.b $FC, $0, $0, $7, $C
	dc.b $8, $0, $0, $8, $C
	dc.b $E8, $9, $0, $9, $F4
	dc.b $F8, $D, $0, $F, $EC
DATAJU8UJA9V4EL_44: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $8, $0, $10, $F4
	dc.b $10, $0, $0, $13, $FC
	dc.b $10, $4, $0, $14, $EC
	dc.b $8, $0, $0, $16, $C
DATAJU8UJA9V4EL_45: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATAJU8UJA9V4EL_46: dc.b $8
	dc.b $FC, $5, $0, $13, $F1
	dc.b $C, $8, $0, $0, $F8
	dc.b $C, $0, $0, $3, $F0
	dc.b $F4, $D, $0, $4, $F0
	dc.b $EC, $8, $0, $C, $F0
	dc.b $4, $0, $0, $F, $0
	dc.b $4, $0, $0, $10, $8
	dc.b $4, $4, $0, $11, $F0
DATAJU8UJA9V4EL_47: dc.b $8
	dc.b $FC, $5, $0, $0, $F1
	dc.b $C, $8, $0, $4, $F8
	dc.b $C, $0, $0, $7, $F0
	dc.b $EC, $8, $0, $8, $F0
	dc.b $4, $0, $0, $B, $0
	dc.b $4, $0, $0, $C, $8
	dc.b $4, $4, $0, $D, $F0
	dc.b $F4, $9, $0, $F, $F0
DATAJU8UJA9V4EL_48: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATAJU8UJA9V4EL_49: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATAJU8UJA9V4EL_4A: dc.b $2
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $9, $0, $C, $F4
DATAJU8UJA9V4EL_4B: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATAJU8UJA9V4EL_4C: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAJU8UJA9V4EL_4D: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAJU8UJA9V4EL_4E: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAJU8UJA9V4EL_4F: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAJU8UJA9V4EL_50: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $C, $4, $0, $9, $F3
	dc.b $4, $8, $0, $B, $F3
DATAJU8UJA9V4EL_51: dc.b $7
	dc.b $C, $8, $0, $0, $F8
	dc.b $C, $0, $0, $3, $F0
	dc.b $F4, $D, $0, $4, $F0
	dc.b $4, $4, $0, $C, $F0
	dc.b $4, $4, $0, $E, $0
	dc.b $EC, $2, $0, $10, $E8
	dc.b $EC, $4, $0, $13, $F0
DATAJU8UJA9V4EL_52: dc.b $4
	dc.b $C, $8, $0, $0, $F1
	dc.b $FC, $D, $0, $3, $F1
	dc.b $F4, $4, $0, $B, $F9
	dc.b $4, $0, $0, $D, $E9
DATAJU8UJA9V4EL_53: dc.b $6
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $C, $0, $6, $F4
	dc.b $FE, $0, $0, $A, $EC
	dc.b $F6, $0, $0, $B, $C
	dc.b $6, $8, $0, $C, $FC
	dc.b $E, $4, $0, $F, $4
DATAJU8UJA9V4EL_54: dc.b $4
	dc.b $F1, $E, $0, $0, $EC
	dc.b $E9, $0, $0, $C, $FC
	dc.b $9, $0, $0, $D, $FC
	dc.b $F1, $2, $0, $E, $C
	even