; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Apr 03 2021 13:40:35 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAG9BVX5L116:
	dc.w $0, DATAG9BVX5L116_1-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_2-DATAG9BVX5L116, DATAG9BVX5L116_3-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_4-DATAG9BVX5L116, DATAG9BVX5L116_5-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_6-DATAG9BVX5L116, DATAG9BVX5L116_7-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_8-DATAG9BVX5L116, DATAG9BVX5L116_9-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_A-DATAG9BVX5L116, DATAG9BVX5L116_B-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_C-DATAG9BVX5L116, DATAG9BVX5L116_D-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_E-DATAG9BVX5L116, DATAG9BVX5L116_F-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_10-DATAG9BVX5L116, DATAG9BVX5L116_11-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_12-DATAG9BVX5L116, DATAG9BVX5L116_13-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_14-DATAG9BVX5L116, DATAG9BVX5L116_15-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_16-DATAG9BVX5L116, DATAG9BVX5L116_17-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_18-DATAG9BVX5L116, DATAG9BVX5L116_19-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_1A-DATAG9BVX5L116, DATAG9BVX5L116_1B-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_1C-DATAG9BVX5L116, DATAG9BVX5L116_1D-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_1E-DATAG9BVX5L116, DATAG9BVX5L116_1F-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_20-DATAG9BVX5L116, DATAG9BVX5L116_21-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_22-DATAG9BVX5L116, DATAG9BVX5L116_23-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_24-DATAG9BVX5L116, DATAG9BVX5L116_25-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_26-DATAG9BVX5L116, DATAG9BVX5L116_27-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_28-DATAG9BVX5L116, DATAG9BVX5L116_29-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_2A-DATAG9BVX5L116, DATAG9BVX5L116_2B-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_2C-DATAG9BVX5L116, DATAG9BVX5L116_2D-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_2E-DATAG9BVX5L116, DATAG9BVX5L116_2F-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_30-DATAG9BVX5L116, DATAG9BVX5L116_31-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_32-DATAG9BVX5L116, DATAG9BVX5L116_33-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_34-DATAG9BVX5L116, DATAG9BVX5L116_35-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_36-DATAG9BVX5L116, DATAG9BVX5L116_37-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_38-DATAG9BVX5L116, DATAG9BVX5L116_39-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_3A-DATAG9BVX5L116, DATAG9BVX5L116_3B-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_3C-DATAG9BVX5L116, DATAG9BVX5L116_3D-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_3E-DATAG9BVX5L116, DATAG9BVX5L116_3F-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_40-DATAG9BVX5L116, DATAG9BVX5L116_41-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_42-DATAG9BVX5L116, DATAG9BVX5L116_43-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_44-DATAG9BVX5L116, DATAG9BVX5L116_45-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_46-DATAG9BVX5L116, DATAG9BVX5L116_47-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_48-DATAG9BVX5L116, DATAG9BVX5L116_49-DATAG9BVX5L116
	dc.w $0, $0
	dc.w $0, DATAG9BVX5L116_4D-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_4E-DATAG9BVX5L116, DATAG9BVX5L116_4F-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_50-DATAG9BVX5L116, DATAG9BVX5L116_51-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_52-DATAG9BVX5L116, DATAG9BVX5L116_53-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_54-DATAG9BVX5L116, DATAG9BVX5L116_55-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_56-DATAG9BVX5L116, DATAG9BVX5L116_57-DATAG9BVX5L116
	dc.w DATAG9BVX5L116_58-DATAG9BVX5L116
DATAG9BVX5L116_1: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATAG9BVX5L116_2: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATAG9BVX5L116_3: dc.b $2
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $E, $0, $8, $F4
DATAG9BVX5L116_4: dc.b $3
	dc.b $FD, $A, $0, $0, $F4
	dc.b $F7, $0, $0, $9, $C
	dc.b $ED, $9, $0, $A, $F4
DATAG9BVX5L116_5: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATAG9BVX5L116_6: dc.b $3
	dc.b $FC, $E, $0, $0, $EC
	dc.b $F6, $0, $0, $C, $C
	dc.b $EC, $9, $0, $D, $F4
DATAG9BVX5L116_7: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATAG9BVX5L116_8: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $6, $0, $6, $5
	dc.b $FD, $8, $0, $C, $ED
	dc.b $5, $9, $0, $F, $F5
	dc.b $15, $0, $0, $15, $FD
DATAG9BVX5L116_9: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATAG9BVX5L116_A: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATAG9BVX5L116_B: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATAG9BVX5L116_C: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATAG9BVX5L116_D: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATAG9BVX5L116_E: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATAG9BVX5L116_F: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATAG9BVX5L116_10: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATAG9BVX5L116_11: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $FC, $4, $0, $6, $FB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $4, $9, $0, $E, $FB
DATAG9BVX5L116_12: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAG9BVX5L116_13: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $F4, $A, $0, $8, $FD
	dc.b $EC, $0, $0, $11, $FD
DATAG9BVX5L116_14: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $D, $0, $0, $6, $FB
	dc.b $F5, $A, $0, $7, $FB
	dc.b $FD, $0, $0, $10, $13
	dc.b $F5, $4, $0, $11, $EB
	dc.b $ED, $4, $0, $13, $F3
DATAG9BVX5L116_15: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $C, $0, $0, $6, $FC
	dc.b $F4, $A, $0, $7, $FC
	dc.b $F4, $4, $0, $10, $EC
	dc.b $EC, $4, $0, $12, $FC
	dc.b $E4, $8, $0, $14, $F4
DATAG9BVX5L116_16: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $3, $4, $0, $6, $FD
	dc.b $EB, $A, $0, $8, $FD
	dc.b $F3, $4, $0, $11, $ED
DATAG9BVX5L116_17: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $5, $8, $0, $6, $FB
	dc.b $F5, $D, $0, $9, $FB
	dc.b $F5, $4, $0, $11, $EB
	dc.b $ED, $8, $0, $13, $F3
DATAG9BVX5L116_18: dc.b $4
	dc.b $EC, $A, $0, $0, $FC
	dc.b $4, $4, $0, $9, $FC
	dc.b $FC, $6, $0, $B, $EC
	dc.b $F4, $4, $0, $11, $EC
DATAG9BVX5L116_19: dc.b $5
	dc.b $EE, $A, $0, $0, $0
	dc.b $6, $4, $0, $9, $0
	dc.b $E, $0, $0, $B, $0
	dc.b $FE, $6, $0, $C, $F0
	dc.b $F6, $4, $0, $12, $F0
DATAG9BVX5L116_1A: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAG9BVX5L116_1B: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAG9BVX5L116_1C: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAG9BVX5L116_1D: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAG9BVX5L116_1E: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $0, $0, $8, $EE
	dc.b $FE, $E, $0, $9, $F6
DATAG9BVX5L116_1F: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAG9BVX5L116_20: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $0, $0, $8, $EE
	dc.b $FE, $E, $0, $9, $F6
DATAG9BVX5L116_21: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAG9BVX5L116_22: dc.b $2
	dc.b $F4, $6, $0, $0, $EF
	dc.b $F4, $B, $0, $6, $FF
DATAG9BVX5L116_23: dc.b $2
	dc.b $F4, $6, $0, $0, $EF
	dc.b $F4, $B, $0, $6, $FF
DATAG9BVX5L116_24: dc.b $2
	dc.b $F4, $6, $0, $0, $EF
	dc.b $F4, $B, $0, $6, $FF
DATAG9BVX5L116_25: dc.b $2
	dc.b $F4, $6, $0, $0, $EF
	dc.b $F4, $B, $0, $6, $FF
DATAG9BVX5L116_26: dc.b $3
	dc.b $F2, $7, $0, $0, $EE
	dc.b $A, $0, $0, $8, $FE
	dc.b $EA, $B, $0, $9, $FE
DATAG9BVX5L116_27: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAG9BVX5L116_28: dc.b $3
	dc.b $F2, $7, $0, $0, $EE
	dc.b $A, $0, $0, $8, $FE
	dc.b $EA, $B, $0, $9, $FE
DATAG9BVX5L116_29: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAG9BVX5L116_2A: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATAG9BVX5L116_2B: dc.b $1
	dc.b $F2, $F, $0, $0, $F1
DATAG9BVX5L116_2C: dc.b $1
	dc.b $EE, $F, $0, $0, $F0
DATAG9BVX5L116_2D: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAG9BVX5L116_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAG9BVX5L116_2F: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATAG9BVX5L116_30: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATAG9BVX5L116_31: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $F7, $1, $0, $C, $C
	dc.b $7, $C, $0, $E, $F4
	dc.b $EF, $0, $0, $12, $C
DATAG9BVX5L116_32: dc.b $4
	dc.b $EB, $9, $8, $0, $F4
	dc.b $FB, $9, $8, $6, $FC
	dc.b $FB, $6, $8, $C, $EC
	dc.b $B, $4, $8, $12, $4
DATAG9BVX5L116_33: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATAG9BVX5L116_34: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $8, $0, $C, $F4
DATAG9BVX5L116_35: dc.b $5
	dc.b $0, $C, $0, $0, $EC
	dc.b $8, $5, $0, $4, $F4
	dc.b $8, $0, $0, $8, $4
	dc.b $E8, $A, $0, $9, $F4
	dc.b $F0, $1, $0, $12, $C
DATAG9BVX5L116_36: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $C, $0, $B, $EC
	dc.b $8, $5, $0, $F, $F4
	dc.b $8, $0, $0, $13, $4
DATAG9BVX5L116_37: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
	dc.b $10, $4, $0, $F, $F4
DATAG9BVX5L116_38: dc.b $3
	dc.b $8, $8, $0, $0, $F4
	dc.b $10, $4, $0, $3, $F4
	dc.b $E8, $B, $0, $5, $F4
DATAG9BVX5L116_39: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
DATAG9BVX5L116_3A: dc.b $2
	dc.b $E8, $F, $0, $0, $F4
	dc.b $8, $8, $0, $10, $F4
DATAG9BVX5L116_3B: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATAG9BVX5L116_3C: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATAG9BVX5L116_3D: dc.b $3
	dc.b $FC, $D, $0, $0, $F2
	dc.b $EC, $9, $0, $8, $F2
	dc.b $C, $4, $0, $E, $2
DATAG9BVX5L116_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAG9BVX5L116_3F: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAG9BVX5L116_40: dc.b $3
	dc.b $F4, $D, $8, $0, $EC
	dc.b $FC, $5, $8, $8, $C
	dc.b $4, $8, $8, $C, $F4
DATAG9BVX5L116_41: dc.b $3
	dc.b $F4, $D, $0, $0, $EC
	dc.b $FC, $0, $0, $8, $C
	dc.b $4, $C, $0, $9, $F4
DATAG9BVX5L116_42: dc.b $3
	dc.b $F4, $D, $8, $0, $F4
	dc.b $FC, $0, $8, $8, $EC
	dc.b $4, $C, $8, $9, $EC
DATAG9BVX5L116_43: dc.b $8
	dc.b $E8, $1, $0, $0, $C
	dc.b $10, $0, $0, $2, $F4
	dc.b $8, $8, $0, $3, $F4
	dc.b $10, $0, $0, $6, $FC
	dc.b $FC, $0, $0, $7, $C
	dc.b $8, $0, $0, $8, $C
	dc.b $E8, $9, $0, $9, $F4
	dc.b $F8, $D, $0, $F, $EC
DATAG9BVX5L116_44: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $8, $0, $10, $F4
	dc.b $10, $0, $0, $13, $FC
	dc.b $10, $4, $0, $14, $EC
	dc.b $8, $0, $0, $16, $C
DATAG9BVX5L116_45: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATAG9BVX5L116_46: dc.b $8
	dc.b $FD, $5, $0, $13, $F1
	dc.b $D, $8, $0, $0, $F8
	dc.b $D, $0, $0, $3, $F0
	dc.b $F5, $D, $0, $4, $F0
	dc.b $ED, $8, $0, $C, $F0
	dc.b $5, $0, $0, $F, $0
	dc.b $5, $0, $0, $10, $8
	dc.b $5, $4, $0, $11, $F0
DATAG9BVX5L116_47: dc.b $8
	dc.b $FD, $5, $0, $0, $F1
	dc.b $D, $8, $0, $4, $F8
	dc.b $D, $0, $0, $7, $F0
	dc.b $ED, $8, $0, $8, $F0
	dc.b $5, $0, $0, $B, $0
	dc.b $5, $0, $0, $C, $8
	dc.b $5, $4, $0, $D, $F0
	dc.b $F5, $9, $0, $F, $F0
DATAG9BVX5L116_48: dc.b $6
	dc.b $FD, $5, $0, $0, $F1
	dc.b $D, $8, $0, $4, $F8
	dc.b $D, $0, $0, $7, $F0
	dc.b $5, $8, $0, $8, $F0
	dc.b $F5, $9, $0, $B, $F0
	dc.b $ED, $8, $0, $11, $F0
DATAG9BVX5L116_49: dc.b $6
	dc.b $FD, $5, $0, $0, $F1
	dc.b $D, $0, $0, $4, $F0
	dc.b $D, $8, $0, $5, $F8
	dc.b $5, $8, $0, $8, $F0
	dc.b $F5, $9, $0, $B, $F0
	dc.b $ED, $8, $0, $11, $F0
DATAG9BVX5L116_4D: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATAG9BVX5L116_4E: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATAG9BVX5L116_4F: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAG9BVX5L116_50: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAG9BVX5L116_51: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAG9BVX5L116_52: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAG9BVX5L116_53: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAG9BVX5L116_54: dc.b $7
	dc.b $D, $8, $0, $0, $F8
	dc.b $D, $0, $0, $3, $F0
	dc.b $F5, $D, $0, $4, $F0
	dc.b $5, $4, $0, $C, $F0
	dc.b $5, $4, $0, $E, $0
	dc.b $ED, $2, $0, $10, $E8
	dc.b $ED, $4, $0, $13, $F0
DATAG9BVX5L116_55: dc.b $4
	dc.b $D, $8, $0, $0, $F5
	dc.b $FD, $D, $0, $3, $F5
	dc.b $F5, $4, $0, $B, $FD
	dc.b $5, $0, $0, $D, $ED
DATAG9BVX5L116_56: dc.b $6
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $C, $0, $6, $F4
	dc.b $FE, $0, $0, $A, $EC
	dc.b $F6, $0, $0, $B, $C
	dc.b $6, $8, $0, $C, $FC
	dc.b $E, $4, $0, $F, $4
DATAG9BVX5L116_57: dc.b $3
	dc.b $ED, $B, $0, $0, $EB
	dc.b $ED, $3, $0, $C, $3
	dc.b $D, $C, $0, $10, $EB
DATAG9BVX5L116_58: dc.b $3
	dc.b $ED, $B, $0, $0, $EB
	dc.b $ED, $3, $0, $C, $3
	dc.b $D, $C, $0, $10, $EB
	even