; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Sep 26 2021 23:12:27 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA36TFDP05QOD:
	dc.w $0, DATA36TFDP05QOD_1-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_2-DATA36TFDP05QOD, DATA36TFDP05QOD_3-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_4-DATA36TFDP05QOD, DATA36TFDP05QOD_5-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_6-DATA36TFDP05QOD, DATA36TFDP05QOD_7-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_8-DATA36TFDP05QOD, DATA36TFDP05QOD_9-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_A-DATA36TFDP05QOD, DATA36TFDP05QOD_B-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_C-DATA36TFDP05QOD, DATA36TFDP05QOD_D-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_E-DATA36TFDP05QOD, DATA36TFDP05QOD_F-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_10-DATA36TFDP05QOD, DATA36TFDP05QOD_11-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_12-DATA36TFDP05QOD, DATA36TFDP05QOD_13-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_14-DATA36TFDP05QOD, DATA36TFDP05QOD_15-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_16-DATA36TFDP05QOD, DATA36TFDP05QOD_17-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_18-DATA36TFDP05QOD, DATA36TFDP05QOD_19-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_1A-DATA36TFDP05QOD, DATA36TFDP05QOD_1B-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_1C-DATA36TFDP05QOD, DATA36TFDP05QOD_1D-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_1E-DATA36TFDP05QOD, DATA36TFDP05QOD_1F-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_20-DATA36TFDP05QOD, DATA36TFDP05QOD_21-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_22-DATA36TFDP05QOD, DATA36TFDP05QOD_23-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_24-DATA36TFDP05QOD, DATA36TFDP05QOD_25-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_26-DATA36TFDP05QOD, DATA36TFDP05QOD_27-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_28-DATA36TFDP05QOD, DATA36TFDP05QOD_29-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_2A-DATA36TFDP05QOD, DATA36TFDP05QOD_2B-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_2C-DATA36TFDP05QOD, DATA36TFDP05QOD_2D-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_2E-DATA36TFDP05QOD, DATA36TFDP05QOD_2F-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_30-DATA36TFDP05QOD, DATA36TFDP05QOD_31-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_32-DATA36TFDP05QOD, DATA36TFDP05QOD_33-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_34-DATA36TFDP05QOD, DATA36TFDP05QOD_35-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_36-DATA36TFDP05QOD, DATA36TFDP05QOD_37-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_38-DATA36TFDP05QOD, DATA36TFDP05QOD_39-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_3A-DATA36TFDP05QOD, DATA36TFDP05QOD_3B-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_3C-DATA36TFDP05QOD, DATA36TFDP05QOD_3D-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_3E-DATA36TFDP05QOD, DATA36TFDP05QOD_3F-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_40-DATA36TFDP05QOD, DATA36TFDP05QOD_41-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_42-DATA36TFDP05QOD, DATA36TFDP05QOD_43-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_44-DATA36TFDP05QOD, DATA36TFDP05QOD_45-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_46-DATA36TFDP05QOD, DATA36TFDP05QOD_47-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_48-DATA36TFDP05QOD, DATA36TFDP05QOD_49-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_4A-DATA36TFDP05QOD, DATA36TFDP05QOD_4B-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_4C-DATA36TFDP05QOD, DATA36TFDP05QOD_4D-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_4E-DATA36TFDP05QOD, DATA36TFDP05QOD_4F-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_50-DATA36TFDP05QOD, DATA36TFDP05QOD_51-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_52-DATA36TFDP05QOD, DATA36TFDP05QOD_53-DATA36TFDP05QOD
	dc.w DATA36TFDP05QOD_54-DATA36TFDP05QOD, DATA36TFDP05QOD_55-DATA36TFDP05QOD
DATA36TFDP05QOD_1: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA36TFDP05QOD_2: dc.b $4
	dc.b $EB, $D, $0, $0, $EB
	dc.b $FB, $9, $0, $8, $EB
	dc.b $FB, $6, $0, $E, $3
	dc.b $B, $4, $0, $14, $EB
DATA36TFDP05QOD_3: dc.b $2
	dc.b $EC, $D, $0, $0, $EB
	dc.b $FC, $E, $0, $8, $F3
DATA36TFDP05QOD_4: dc.b $2
	dc.b $FD, $A, $0, $0, $F4
	dc.b $ED, $9, $0, $9, $F4
DATA36TFDP05QOD_5: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATA36TFDP05QOD_6: dc.b $2
	dc.b $FC, $E, $0, $0, $EC
	dc.b $EC, $9, $0, $C, $F4
DATA36TFDP05QOD_7: dc.b $3
	dc.b $ED, $D, $0, $0, $EB
	dc.b $FD, $C, $0, $8, $F3
	dc.b $5, $9, $0, $C, $F3
DATA36TFDP05QOD_8: dc.b $5
	dc.b $EC, $9, $0, $0, $EA
	dc.b $EC, $6, $0, $6, $2
	dc.b $FC, $8, $0, $C, $EA
	dc.b $4, $9, $0, $F, $F2
	dc.b $14, $0, $0, $15, $FA
DATA36TFDP05QOD_9: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATA36TFDP05QOD_A: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATA36TFDP05QOD_B: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATA36TFDP05QOD_C: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATA36TFDP05QOD_D: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATA36TFDP05QOD_E: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATA36TFDP05QOD_F: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATA36TFDP05QOD_10: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATA36TFDP05QOD_11: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $FC, $4, $0, $6, $FB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $4, $9, $0, $E, $FB
DATA36TFDP05QOD_12: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATA36TFDP05QOD_13: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $F4, $A, $0, $8, $FD
	dc.b $EC, $0, $0, $11, $FD
DATA36TFDP05QOD_14: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $D, $0, $0, $6, $FB
	dc.b $F5, $A, $0, $7, $FB
	dc.b $FD, $0, $0, $10, $13
	dc.b $F5, $4, $0, $11, $EB
	dc.b $ED, $4, $0, $13, $F3
DATA36TFDP05QOD_15: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $C, $0, $0, $6, $FC
	dc.b $F4, $A, $0, $7, $FC
	dc.b $F4, $4, $0, $10, $EC
	dc.b $EC, $4, $0, $12, $FC
	dc.b $E4, $8, $0, $14, $F4
DATA36TFDP05QOD_16: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $3, $4, $0, $6, $FD
	dc.b $EB, $A, $0, $8, $FD
	dc.b $F3, $4, $0, $11, $ED
DATA36TFDP05QOD_17: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $5, $8, $0, $6, $FB
	dc.b $F5, $D, $0, $9, $FB
	dc.b $F5, $4, $0, $11, $EB
	dc.b $ED, $8, $0, $13, $F3
DATA36TFDP05QOD_18: dc.b $4
	dc.b $EC, $A, $0, $0, $FC
	dc.b $4, $4, $0, $9, $FC
	dc.b $FC, $6, $0, $B, $EC
	dc.b $F4, $4, $0, $11, $EC
DATA36TFDP05QOD_19: dc.b $5
	dc.b $EE, $A, $0, $0, $0
	dc.b $6, $4, $0, $9, $0
	dc.b $E, $0, $0, $B, $0
	dc.b $FE, $6, $0, $C, $F0
	dc.b $F6, $4, $0, $12, $F0
DATA36TFDP05QOD_1A: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATA36TFDP05QOD_1B: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATA36TFDP05QOD_1C: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATA36TFDP05QOD_1D: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATA36TFDP05QOD_1E: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $0, $0, $8, $EE
	dc.b $FE, $E, $0, $9, $F6
DATA36TFDP05QOD_1F: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA36TFDP05QOD_20: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $0, $0, $8, $EE
	dc.b $FE, $E, $0, $9, $F6
DATA36TFDP05QOD_21: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA36TFDP05QOD_22: dc.b $2
	dc.b $EF, $7, $0, $0, $F2
	dc.b $F7, $B, $0, $8, $2
DATA36TFDP05QOD_23: dc.b $2
	dc.b $F4, $6, $0, $0, $EF
	dc.b $F4, $B, $0, $6, $FF
DATA36TFDP05QOD_24: dc.b $2
	dc.b $F3, $F, $0, $0, $F2
	dc.b $FB, $2, $0, $10, $12
DATA36TFDP05QOD_25: dc.b $2
	dc.b $F4, $6, $0, $0, $EF
	dc.b $F4, $B, $0, $6, $FF
DATA36TFDP05QOD_26: dc.b $3
	dc.b $F2, $7, $0, $0, $EE
	dc.b $A, $0, $0, $8, $FE
	dc.b $EA, $B, $0, $9, $FE
DATA36TFDP05QOD_27: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA36TFDP05QOD_28: dc.b $3
	dc.b $F2, $7, $0, $0, $EE
	dc.b $A, $0, $0, $8, $FE
	dc.b $EA, $B, $0, $9, $FE
DATA36TFDP05QOD_29: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA36TFDP05QOD_2A: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA36TFDP05QOD_2B: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA36TFDP05QOD_2C: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA36TFDP05QOD_2D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA36TFDP05QOD_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA36TFDP05QOD_2F: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATA36TFDP05QOD_30: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATA36TFDP05QOD_31: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $F7, $1, $0, $C, $C
	dc.b $7, $C, $0, $E, $F4
	dc.b $EF, $0, $0, $12, $C
DATA36TFDP05QOD_32: dc.b $4
	dc.b $EB, $9, $8, $0, $F4
	dc.b $FB, $9, $8, $6, $FC
	dc.b $FB, $6, $8, $C, $EC
	dc.b $B, $4, $8, $12, $4
DATA36TFDP05QOD_33: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATA36TFDP05QOD_34: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $8, $0, $C, $F4
DATA36TFDP05QOD_35: dc.b $5
	dc.b $0, $C, $0, $0, $EC
	dc.b $8, $5, $0, $4, $F4
	dc.b $8, $0, $0, $8, $4
	dc.b $E8, $A, $0, $9, $F4
	dc.b $F0, $1, $0, $12, $C
DATA36TFDP05QOD_36: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $C, $0, $B, $EC
	dc.b $8, $5, $0, $F, $F4
	dc.b $8, $0, $0, $13, $4
DATA36TFDP05QOD_37: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
	dc.b $10, $4, $0, $F, $F4
DATA36TFDP05QOD_38: dc.b $3
	dc.b $8, $8, $0, $0, $F4
	dc.b $10, $4, $0, $3, $F4
	dc.b $E8, $B, $0, $5, $F4
DATA36TFDP05QOD_39: dc.b $2
	dc.b $E8, $B, $0, $0, $F3
	dc.b $8, $8, $0, $C, $F3
DATA36TFDP05QOD_3A: dc.b $2
	dc.b $E8, $F, $0, $0, $F3
	dc.b $8, $8, $0, $10, $F3
DATA36TFDP05QOD_3B: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATA36TFDP05QOD_3C: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATA36TFDP05QOD_3D: dc.b $3
	dc.b $FC, $D, $0, $0, $F2
	dc.b $EC, $9, $0, $8, $F2
	dc.b $C, $4, $0, $E, $2
DATA36TFDP05QOD_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA36TFDP05QOD_3F: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATA36TFDP05QOD_40: dc.b $3
	dc.b $F4, $D, $8, $0, $EC
	dc.b $FC, $5, $8, $8, $C
	dc.b $4, $8, $8, $C, $F4
DATA36TFDP05QOD_41: dc.b $3
	dc.b $F4, $D, $0, $0, $EC
	dc.b $FC, $0, $0, $8, $C
	dc.b $4, $C, $0, $9, $F4
DATA36TFDP05QOD_42: dc.b $3
	dc.b $F4, $D, $8, $0, $F4
	dc.b $FC, $0, $8, $8, $EC
	dc.b $4, $C, $8, $9, $EC
DATA36TFDP05QOD_43: dc.b $8
	dc.b $E8, $1, $0, $0, $C
	dc.b $10, $0, $0, $2, $F4
	dc.b $8, $8, $0, $3, $F4
	dc.b $10, $0, $0, $6, $FC
	dc.b $FC, $0, $0, $7, $C
	dc.b $8, $0, $0, $8, $C
	dc.b $E8, $9, $0, $9, $F4
	dc.b $F8, $D, $0, $F, $EC
DATA36TFDP05QOD_44: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $8, $0, $10, $F4
	dc.b $10, $0, $0, $13, $FC
	dc.b $10, $4, $0, $14, $EC
	dc.b $8, $0, $0, $16, $C
DATA36TFDP05QOD_45: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATA36TFDP05QOD_46: dc.b $8
	dc.b $FC, $5, $0, $13, $F1
	dc.b $C, $8, $0, $0, $F8
	dc.b $C, $0, $0, $3, $F0
	dc.b $F4, $D, $0, $4, $F0
	dc.b $EC, $8, $0, $C, $F0
	dc.b $4, $0, $0, $F, $0
	dc.b $4, $0, $0, $10, $8
	dc.b $4, $4, $0, $11, $F0
DATA36TFDP05QOD_47: dc.b $8
	dc.b $FC, $5, $0, $0, $F1
	dc.b $C, $8, $0, $4, $F8
	dc.b $C, $0, $0, $7, $F0
	dc.b $EC, $8, $0, $8, $F0
	dc.b $4, $0, $0, $B, $0
	dc.b $4, $0, $0, $C, $8
	dc.b $4, $4, $0, $D, $F0
	dc.b $F4, $9, $0, $F, $F0
DATA36TFDP05QOD_48: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATA36TFDP05QOD_49: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATA36TFDP05QOD_4A: dc.b $2
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $9, $0, $C, $F4
DATA36TFDP05QOD_4B: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATA36TFDP05QOD_4C: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA36TFDP05QOD_4D: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATA36TFDP05QOD_4E: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATA36TFDP05QOD_4F: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATA36TFDP05QOD_50: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $C, $4, $0, $9, $F3
	dc.b $4, $8, $0, $B, $F3
DATA36TFDP05QOD_51: dc.b $7
	dc.b $C, $8, $0, $0, $F8
	dc.b $C, $0, $0, $3, $F0
	dc.b $F4, $D, $0, $4, $F0
	dc.b $4, $4, $0, $C, $F0
	dc.b $4, $4, $0, $E, $0
	dc.b $EC, $2, $0, $10, $E8
	dc.b $EC, $4, $0, $13, $F0
DATA36TFDP05QOD_52: dc.b $4
	dc.b $C, $8, $0, $0, $F1
	dc.b $FC, $D, $0, $3, $F1
	dc.b $F4, $4, $0, $B, $F9
	dc.b $4, $0, $0, $D, $E9
DATA36TFDP05QOD_53: dc.b $6
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $C, $0, $6, $F4
	dc.b $FE, $0, $0, $A, $EC
	dc.b $F6, $0, $0, $B, $C
	dc.b $6, $8, $0, $C, $FC
	dc.b $E, $4, $0, $F, $4
DATA36TFDP05QOD_54: dc.b $3
	dc.b $ED, $B, $0, $0, $EB
	dc.b $ED, $3, $0, $C, $3
	dc.b $D, $C, $0, $10, $EB
DATA36TFDP05QOD_55: dc.b $3
	dc.b $ED, $B, $0, $0, $EB
	dc.b $ED, $3, $0, $C, $3
	dc.b $D, $C, $0, $10, $EB
	even