; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Nov 11 2021 20:30:07 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAFGMU2A83YZI:
	dc.w DATAFGMU2A83YZI_0-DATAFGMU2A83YZI, DATAFGMU2A83YZI_1-DATAFGMU2A83YZI
	dc.w DATAFGMU2A83YZI_2-DATAFGMU2A83YZI, DATAFGMU2A83YZI_3-DATAFGMU2A83YZI
	dc.w DATAFGMU2A83YZI_4-DATAFGMU2A83YZI, DATAFGMU2A83YZI_5-DATAFGMU2A83YZI
	dc.w DATAFGMU2A83YZI_6-DATAFGMU2A83YZI, DATAFGMU2A83YZI_7-DATAFGMU2A83YZI
	dc.w DATAFGMU2A83YZI_8-DATAFGMU2A83YZI
DATAFGMU2A83YZI_0: dc.b $4
	dc.b $F8, $5, $0, $1C, $F0
	dc.b $F8, $5, $0, $0, $0
	dc.b $F8, $5, $0, $42, $10
	dc.b $F8, $5, $0, $2A, $E0
DATAFGMU2A83YZI_1: dc.b $6
	dc.b $E8, $D, $1, $4A, $B0
	dc.b $E8, $1, $1, $62, $D0
	dc.b $E8, $9, $1, $64, $18
	dc.b $E8, $D, $1, $6A, $30
	dc.b $E7, $4, $0, $6E, $CD
	dc.b $EF, $4, $18, $6E, $CD
DATAFGMU2A83YZI_2: dc.b $7
	dc.b $F8, $D, $1, $52, $B0
	dc.b $F8, $D, $0, $66, $D9
	dc.b $F8, $1, $1, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F8, $28
	dc.b $F8, $1, $1, $70, $48
DATAFGMU2A83YZI_3: dc.b $0
DATAFGMU2A83YZI_4: dc.b $4
	dc.b $E8, $D, $FF, $D1, $B0
	dc.b $E8, $D, $FF, $D9, $D0
	dc.b $E8, $1, $FF, $E1, $F0
	dc.b $E8, $6, $1F, $E3, $40
DATAFGMU2A83YZI_5: dc.b $4
	dc.b $E8, $D, $FF, $D1, $B0
	dc.b $E8, $D, $FF, $D9, $D0
	dc.b $E8, $1, $FF, $E1, $F0
	dc.b $E8, $6, $1F, $E9, $40
DATAFGMU2A83YZI_6: dc.b $3
	dc.b $E8, $D, $FF, $D1, $B0
	dc.b $E8, $D, $FF, $D9, $D0
	dc.b $E8, $1, $FF, $E1, $F0
DATAFGMU2A83YZI_7: dc.b $A
	dc.b $F8, $5, $0, $3E, $8
	dc.b $F8, $5, $0, $42, $18
	dc.b $F8, $5, $0, $0, $28
	dc.b $F8, $5, $0, $18, $38
	dc.b $F8, $5, $0, $10, $48
	dc.b $F8, $5, $0, $4, $A8
	dc.b $F8, $5, $0, $32, $B8
	dc.b $F8, $5, $0, $2E, $C8
	dc.b $F8, $5, $0, $46, $D8
	dc.b $F8, $5, $0, $3E, $E8
DATAFGMU2A83YZI_8: dc.b $7
	dc.b $F8, $5, $0, $1C, $10
	dc.b $F8, $5, $0, $0, $20
	dc.b $F8, $5, $0, $42, $30
	dc.b $F8, $5, $0, $4A, $C1
	dc.b $F8, $5, $0, $32, $D1
	dc.b $F8, $5, $0, $46, $E1
	dc.b $F8, $5, $0, $2A, $0
	even