; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun May 23 2021 15:02:20 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA76661M3VCCL:
	dc.w DATA76661M3VCCL_0-DATA76661M3VCCL, DATA76661M3VCCL_1-DATA76661M3VCCL
	dc.w DATA76661M3VCCL_2-DATA76661M3VCCL, DATA76661M3VCCL_3-DATA76661M3VCCL
	dc.w DATA76661M3VCCL_4-DATA76661M3VCCL, DATA76661M3VCCL_5-DATA76661M3VCCL
	dc.w DATA76661M3VCCL_6-DATA76661M3VCCL, DATA76661M3VCCL_7-DATA76661M3VCCL
	dc.w DATA76661M3VCCL_8-DATA76661M3VCCL
DATA76661M3VCCL_0: dc.b $4
	dc.b $F8, $9, $0, $80, $DC
	dc.b $F8, $5, $0, $1C, $F4
	dc.b $F8, $5, $0, $0, $4
	dc.b $F8, $5, $0, $42, $14
DATA76661M3VCCL_1: dc.b $6
	dc.b $E8, $D, $1, $4A, $B0
	dc.b $E8, $1, $1, $62, $D0
	dc.b $E8, $9, $1, $64, $18
	dc.b $E8, $D, $1, $6A, $30
	dc.b $E7, $4, $0, $6E, $CD
	dc.b $EF, $4, $18, $6E, $CD
DATA76661M3VCCL_2: dc.b $7
	dc.b $F8, $D, $1, $52, $B0
	dc.b $F8, $D, $0, $66, $D9
	dc.b $F8, $1, $1, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F8, $28
	dc.b $F8, $1, $1, $70, $48
DATA76661M3VCCL_3: dc.b $0
DATA76661M3VCCL_4: dc.b $4
	dc.b $E8, $D, $FF, $D1, $B0
	dc.b $E8, $D, $FF, $D9, $D0
	dc.b $E8, $1, $FF, $E1, $F0
	dc.b $E8, $6, $1F, $E3, $40
DATA76661M3VCCL_5: dc.b $4
	dc.b $E8, $D, $FF, $D1, $B0
	dc.b $E8, $D, $FF, $D9, $D0
	dc.b $E8, $1, $FF, $E1, $F0
	dc.b $E8, $6, $1F, $E9, $40
DATA76661M3VCCL_6: dc.b $3
	dc.b $E8, $D, $FF, $D1, $B0
	dc.b $E8, $D, $FF, $D9, $D0
	dc.b $E8, $1, $FF, $E1, $F0
DATA76661M3VCCL_7: dc.b $A
	dc.b $F8, $5, $0, $3E, $8
	dc.b $F8, $5, $0, $42, $18
	dc.b $F8, $5, $0, $0, $28
	dc.b $F8, $5, $0, $18, $38
	dc.b $F8, $5, $0, $10, $48
	dc.b $F8, $5, $0, $4, $A8
	dc.b $F8, $5, $0, $32, $B8
	dc.b $F8, $5, $0, $2E, $C8
	dc.b $F8, $5, $0, $46, $D8
	dc.b $F8, $5, $0, $3E, $E8
DATA76661M3VCCL_8: dc.b $7
	dc.b $F8, $9, $0, $80, $FC
	dc.b $F8, $5, $0, $1C, $14
	dc.b $F8, $5, $0, $0, $24
	dc.b $F8, $5, $0, $42, $34
	dc.b $F8, $5, $0, $4A, $BD
	dc.b $F8, $5, $0, $32, $CD
	dc.b $F8, $5, $0, $46, $DD
	even