; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu May 20 2021 22:44:15 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA7FRT3Z56ERD:
	dc.w DATA7FRT3Z56ERD_0-DATA7FRT3Z56ERD, DATA7FRT3Z56ERD_1-DATA7FRT3Z56ERD
	dc.w DATA7FRT3Z56ERD_2-DATA7FRT3Z56ERD
DATA7FRT3Z56ERD_0: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATA7FRT3Z56ERD_1: dc.b $1
	dc.b $F4, $A, $20, $0, $F4
DATA7FRT3Z56ERD_2: dc.b $0
	even