; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Nov 11 2021 20:29:06 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAP1E7TFSDC3I:
	dc.w DATAP1E7TFSDC3I_0-DATAP1E7TFSDC3I, DATAP1E7TFSDC3I_1-DATAP1E7TFSDC3I
	dc.w DATAP1E7TFSDC3I_2-DATAP1E7TFSDC3I, DATAP1E7TFSDC3I_3-DATAP1E7TFSDC3I
	dc.w DATAP1E7TFSDC3I_4-DATAP1E7TFSDC3I, DATAP1E7TFSDC3I_5-DATAP1E7TFSDC3I
	dc.w DATAP1E7TFSDC3I_6-DATAP1E7TFSDC3I, DATAP1E7TFSDC3I_7-DATAP1E7TFSDC3I
	dc.w DATAP1E7TFSDC3I_8-DATAP1E7TFSDC3I, DATAP1E7TFSDC3I_9-DATAP1E7TFSDC3I
	dc.w DATAP1E7TFSDC3I_A-DATAP1E7TFSDC3I, DATAP1E7TFSDC3I_B-DATAP1E7TFSDC3I
	dc.w DATAP1E7TFSDC3I_C-DATAP1E7TFSDC3I, DATAP1E7TFSDC3I_D-DATAP1E7TFSDC3I
DATAP1E7TFSDC3I_0: dc.b $9
	dc.b $F8, $5, $0, $18, $B4
	dc.b $F8, $5, $0, $3A, $C4
	dc.b $F8, $5, $0, $10, $D4
	dc.b $F8, $5, $0, $10, $E4
	dc.b $F8, $5, $0, $2E, $F4
	dc.b $F8, $5, $0, $1C, $14
	dc.b $F8, $1, $0, $20, $24
	dc.b $F8, $5, $0, $26, $2C
	dc.b $F8, $5, $0, $26, $3C
DATAP1E7TFSDC3I_1: dc.b $9
	dc.b $F8, $5, $0, $26, $BC
	dc.b $F8, $5, $0, $0, $CC
	dc.b $F8, $5, $0, $4, $DC
	dc.b $F8, $5, $0, $4A, $EC
	dc.b $F8, $5, $0, $3A, $FC
	dc.b $F8, $1, $0, $20, $C
	dc.b $F8, $5, $0, $2E, $14
	dc.b $F8, $5, $0, $42, $24
	dc.b $F8, $5, $0, $1C, $34
DATAP1E7TFSDC3I_2: dc.b $6
	dc.b $F8, $5, $0, $2A, $CF
	dc.b $F8, $5, $0, $0, $E0
	dc.b $F8, $5, $0, $3A, $F0
	dc.b $F8, $5, $0, $4, $0
	dc.b $F8, $5, $0, $26, $10
	dc.b $F8, $5, $0, $10, $20
DATAP1E7TFSDC3I_3: dc.b $9
	dc.b $F8, $5, $0, $3E, $B4
	dc.b $F8, $5, $0, $42, $C4
	dc.b $F8, $5, $0, $0, $D4
	dc.b $F8, $5, $0, $3A, $E4
	dc.b $F8, $5, $0, $26, $4
	dc.b $F8, $1, $0, $20, $14
	dc.b $F8, $5, $0, $18, $1C
	dc.b $F8, $5, $0, $1C, $2C
	dc.b $F8, $5, $0, $42, $3C
DATAP1E7TFSDC3I_4: dc.b $9
	dc.b $F8, $5, $0, $3E, $BC
	dc.b $F8, $5, $0, $36, $CC
	dc.b $F8, $5, $0, $0, $DC
	dc.b $F8, $5, $0, $3A, $EC
	dc.b $F8, $5, $0, $22, $FC
	dc.b $F8, $5, $0, $26, $C
	dc.b $F8, $1, $0, $20, $1C
	dc.b $F8, $5, $0, $2E, $24
	dc.b $F8, $5, $0, $18, $34
DATAP1E7TFSDC3I_5: dc.b $9
	dc.b $F8, $5, $0, $8, $B0
	dc.b $F8, $5, $0, $26, $C0
	dc.b $F8, $5, $0, $32, $D0
	dc.b $F8, $5, $0, $8, $E0
	dc.b $F8, $5, $0, $22, $F0
	dc.b $F8, $5, $0, $32, $20
	dc.b $F8, $5, $0, $3A, $30
	dc.b $F8, $5, $0, $22, $40
	dc.b $F8, $5, $0, $2A, $10
DATAP1E7TFSDC3I_6: dc.b $4
	dc.b $F8, $5, $0, $4E, $E0
	dc.b $F8, $5, $0, $32, $F0
	dc.b $F8, $5, $0, $2E, $0
	dc.b $F8, $5, $0, $10, $10
DATAP1E7TFSDC3I_7: dc.b $B
	dc.b $F8, $1, $0, $20, $A0
	dc.b $F8, $5, $0, $8, $A8
	dc.b $F8, $5, $0, $10, $B8
	dc.b $F8, $5, $0, $2A, $D8
	dc.b $F8, $5, $0, $32, $E8
	dc.b $F8, $5, $0, $46, $F8
	dc.b $F8, $5, $0, $2E, $8
	dc.b $F8, $5, $0, $42, $18
	dc.b $F8, $5, $0, $0, $28
	dc.b $F8, $1, $0, $20, $38
	dc.b $F8, $5, $0, $2E, $40
DATAP1E7TFSDC3I_8: dc.b $B
	dc.b $F8, $5, $0, $8, $9C
	dc.b $F8, $5, $0, $32, $AC
	dc.b $F8, $5, $0, $3E, $BC
	dc.b $F8, $5, $0, $2A, $CC
	dc.b $F8, $1, $0, $20, $DC
	dc.b $F8, $5, $0, $8, $E4
	dc.b $F8, $5, $0, $3E, $4
	dc.b $F8, $5, $0, $36, $14
	dc.b $F8, $5, $0, $0, $24
	dc.b $F8, $5, $0, $8, $34
	dc.b $F8, $5, $0, $10, $44
DATAP1E7TFSDC3I_9: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $2, $0, $57, $C
DATAP1E7TFSDC3I_A: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $6, $0, $5A, $8
DATAP1E7TFSDC3I_B: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $6, $0, $60, $8
DATAP1E7TFSDC3I_C: dc.b $D
	dc.b $E4, $C, $0, $70, $F4
	dc.b $E4, $2, $0, $74, $14
	dc.b $EC, $4, $0, $77, $EC
	dc.b $F4, $5, $0, $79, $E4
	dc.b $14, $C, $18, $70, $EC
	dc.b $4, $2, $18, $74, $E4
	dc.b $C, $4, $18, $77, $4
	dc.b $FC, $5, $18, $79, $C
	dc.b $EC, $8, $0, $7D, $FC
	dc.b $F4, $C, $0, $7C, $F4
	dc.b $FC, $8, $0, $7C, $F4
	dc.b $4, $C, $0, $7C, $EC
	dc.b $C, $8, $0, $7C, $EC
DATAP1E7TFSDC3I_D: dc.b $5
	dc.b $F8, $5, $0, $14, $DC
	dc.b $F8, $1, $0, $20, $EC
	dc.b $F8, $5, $0, $2E, $F4
	dc.b $F8, $5, $0, $0, $4
	dc.b $F8, $5, $0, $26, $14
	even