; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Mar 28 2021 22:21:50 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAVB7MU9FC7K:
	dc.w DATAVB7MU9FC7K_0-DATAVB7MU9FC7K, DATAVB7MU9FC7K_1-DATAVB7MU9FC7K
	dc.w DATAVB7MU9FC7K_2-DATAVB7MU9FC7K, DATAVB7MU9FC7K_3-DATAVB7MU9FC7K
	dc.w DATAVB7MU9FC7K_4-DATAVB7MU9FC7K, DATAVB7MU9FC7K_5-DATAVB7MU9FC7K
	dc.w DATAVB7MU9FC7K_6-DATAVB7MU9FC7K, DATAVB7MU9FC7K_7-DATAVB7MU9FC7K
	dc.w DATAVB7MU9FC7K_8-DATAVB7MU9FC7K, DATAVB7MU9FC7K_9-DATAVB7MU9FC7K
	dc.w DATAVB7MU9FC7K_A-DATAVB7MU9FC7K, DATAVB7MU9FC7K_B-DATAVB7MU9FC7K
	dc.w DATAVB7MU9FC7K_C-DATAVB7MU9FC7K, DATAVB7MU9FC7K_D-DATAVB7MU9FC7K
DATAVB7MU9FC7K_0: dc.b $9
	dc.b $F8, $5, $0, $18, $B4
	dc.b $F8, $5, $0, $3A, $C4
	dc.b $F8, $5, $0, $10, $D4
	dc.b $F8, $5, $0, $10, $E4
	dc.b $F8, $5, $0, $2E, $F4
	dc.b $F8, $5, $0, $1C, $14
	dc.b $F8, $1, $0, $20, $24
	dc.b $F8, $5, $0, $26, $2C
	dc.b $F8, $5, $0, $26, $3C
DATAVB7MU9FC7K_1: dc.b $9
	dc.b $F8, $5, $0, $26, $BC
	dc.b $F8, $5, $0, $0, $CC
	dc.b $F8, $5, $0, $4, $DC
	dc.b $F8, $5, $0, $4A, $EC
	dc.b $F8, $5, $0, $3A, $FC
	dc.b $F8, $1, $0, $20, $C
	dc.b $F8, $5, $0, $2E, $14
	dc.b $F8, $5, $0, $42, $24
	dc.b $F8, $5, $0, $1C, $34
DATAVB7MU9FC7K_2: dc.b $6
	dc.b $F8, $5, $0, $2A, $CF
	dc.b $F8, $5, $0, $0, $E0
	dc.b $F8, $5, $0, $3A, $F0
	dc.b $F8, $5, $0, $4, $0
	dc.b $F8, $5, $0, $26, $10
	dc.b $F8, $5, $0, $10, $20
DATAVB7MU9FC7K_3: dc.b $9
	dc.b $F8, $5, $0, $3E, $B4
	dc.b $F8, $5, $0, $42, $C4
	dc.b $F8, $5, $0, $0, $D4
	dc.b $F8, $5, $0, $3A, $E4
	dc.b $F8, $5, $0, $26, $4
	dc.b $F8, $1, $0, $20, $14
	dc.b $F8, $5, $0, $18, $1C
	dc.b $F8, $5, $0, $1C, $2C
	dc.b $F8, $5, $0, $42, $3C
DATAVB7MU9FC7K_4: dc.b $9
	dc.b $F8, $5, $0, $3E, $C0
	dc.b $F8, $5, $0, $36, $D0
	dc.b $F8, $5, $0, $0, $E0
	dc.b $F8, $5, $0, $3A, $F0
	dc.b $F8, $5, $0, $22, $0
	dc.b $F8, $5, $0, $26, $10
	dc.b $F8, $1, $0, $20, $20
	dc.b $F8, $5, $0, $2E, $28
	dc.b $F8, $5, $0, $18, $38
DATAVB7MU9FC7K_5: dc.b $9
	dc.b $F8, $5, $0, $8, $C0
	dc.b $F8, $5, $0, $26, $D0
	dc.b $F8, $5, $0, $32, $E0
	dc.b $F8, $5, $0, $8, $F0
	dc.b $F8, $5, $0, $22, $0
	dc.b $F8, $5, $0, $32, $30
	dc.b $F8, $5, $0, $3A, $40
	dc.b $F8, $5, $0, $22, $50
	dc.b $F8, $9, $0, $80, $18
DATAVB7MU9FC7K_6: dc.b $4
	dc.b $F8, $5, $0, $4E, $E0
	dc.b $F8, $5, $0, $32, $F0
	dc.b $F8, $5, $0, $2E, $0
	dc.b $F8, $5, $0, $10, $10
DATAVB7MU9FC7K_7: dc.b $B
	dc.b $F8, $1, $0, $20, $A0
	dc.b $F8, $5, $0, $8, $A8
	dc.b $F8, $5, $0, $10, $B8
	dc.b $F8, $5, $0, $2A, $D8
	dc.b $F8, $5, $0, $32, $E8
	dc.b $F8, $5, $0, $46, $F8
	dc.b $F8, $5, $0, $2E, $8
	dc.b $F8, $5, $0, $42, $18
	dc.b $F8, $5, $0, $0, $28
	dc.b $F8, $1, $0, $20, $38
	dc.b $F8, $5, $0, $2E, $40
DATAVB7MU9FC7K_8: dc.b $B
	dc.b $F8, $5, $0, $8, $9C
	dc.b $F8, $5, $0, $32, $AC
	dc.b $F8, $5, $0, $3E, $BC
	dc.b $F8, $5, $0, $2A, $CC
	dc.b $F8, $1, $0, $20, $DC
	dc.b $F8, $5, $0, $8, $E4
	dc.b $F8, $5, $0, $3E, $4
	dc.b $F8, $5, $0, $36, $14
	dc.b $F8, $5, $0, $0, $24
	dc.b $F8, $5, $0, $8, $34
	dc.b $F8, $5, $0, $10, $44
DATAVB7MU9FC7K_9: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $2, $0, $57, $C
DATAVB7MU9FC7K_A: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $6, $0, $5A, $8
DATAVB7MU9FC7K_B: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $6, $0, $60, $8
DATAVB7MU9FC7K_C: dc.b $D
	dc.b $E4, $C, $0, $70, $F4
	dc.b $E4, $2, $0, $74, $14
	dc.b $EC, $4, $0, $77, $EC
	dc.b $F4, $5, $0, $79, $E4
	dc.b $14, $C, $18, $70, $EC
	dc.b $4, $2, $18, $74, $E4
	dc.b $C, $4, $18, $77, $4
	dc.b $FC, $5, $18, $79, $C
	dc.b $EC, $8, $0, $7D, $FC
	dc.b $F4, $C, $0, $7C, $F4
	dc.b $FC, $8, $0, $7C, $F4
	dc.b $4, $C, $0, $7C, $EC
	dc.b $C, $8, $0, $7C, $EC
DATAVB7MU9FC7K_D: dc.b $5
	dc.b $F8, $5, $0, $14, $DC
	dc.b $F8, $1, $0, $20, $EC
	dc.b $F8, $5, $0, $2E, $F4
	dc.b $F8, $5, $0, $0, $4
	dc.b $F8, $5, $0, $26, $14
	even