; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Jul 08 2021 21:40:58 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5E3YW3C9M1U:
	dc.w DATA5E3YW3C9M1U_0-DATA5E3YW3C9M1U, DATA5E3YW3C9M1U_1-DATA5E3YW3C9M1U
	dc.w DATA5E3YW3C9M1U_2-DATA5E3YW3C9M1U, DATA5E3YW3C9M1U_3-DATA5E3YW3C9M1U
	dc.w DATA5E3YW3C9M1U_4-DATA5E3YW3C9M1U, DATA5E3YW3C9M1U_5-DATA5E3YW3C9M1U
	dc.w DATA5E3YW3C9M1U_6-DATA5E3YW3C9M1U, DATA5E3YW3C9M1U_7-DATA5E3YW3C9M1U
	dc.w DATA5E3YW3C9M1U_8-DATA5E3YW3C9M1U, DATA5E3YW3C9M1U_9-DATA5E3YW3C9M1U
	dc.w DATA5E3YW3C9M1U_A-DATA5E3YW3C9M1U, DATA5E3YW3C9M1U_B-DATA5E3YW3C9M1U
	dc.w DATA5E3YW3C9M1U_C-DATA5E3YW3C9M1U, DATA5E3YW3C9M1U_D-DATA5E3YW3C9M1U
DATA5E3YW3C9M1U_0: dc.b $9
	dc.b $F8, $5, $0, $18, $B4
	dc.b $F8, $5, $0, $3A, $C4
	dc.b $F8, $5, $0, $10, $D4
	dc.b $F8, $5, $0, $10, $E4
	dc.b $F8, $5, $0, $2E, $F4
	dc.b $F8, $5, $0, $1C, $14
	dc.b $F8, $1, $0, $20, $24
	dc.b $F8, $5, $0, $26, $2C
	dc.b $F8, $5, $0, $26, $3C
DATA5E3YW3C9M1U_1: dc.b $D
	dc.b $3, $5, $0, $18, $C9
	dc.b $FE, $5, $0, $10, $DB
	dc.b $6, $5, $0, $42, $EC
	dc.b $FC, $5, $0, $32, $7
	dc.b $4, $5, $0, $46, $18
	dc.b $FB, $5, $0, $42, $27
	dc.b $F6, $F, $0, $70, $65
	dc.b $F5, $F, $0, $70, $61
	dc.b $F3, $F, $0, $70, $5C
	dc.b $F4, $F, $0, $70, $5E
	dc.b $F5, $F, $0, $70, $62
	dc.b $F4, $F, $0, $70, $60
	dc.b $F2, $F, $0, $70, $62
DATA5E3YW3C9M1U_2: dc.b $6
	dc.b $F8, $5, $0, $2A, $CF
	dc.b $F8, $5, $0, $0, $E0
	dc.b $F8, $5, $0, $3A, $F0
	dc.b $F8, $5, $0, $4, $0
	dc.b $F8, $5, $0, $26, $10
	dc.b $F8, $5, $0, $10, $20
DATA5E3YW3C9M1U_3: dc.b $9
	dc.b $F8, $5, $0, $3E, $B4
	dc.b $F8, $5, $0, $42, $C4
	dc.b $F8, $5, $0, $0, $D4
	dc.b $F8, $5, $0, $3A, $E4
	dc.b $F8, $5, $0, $26, $4
	dc.b $F8, $1, $0, $20, $14
	dc.b $F8, $5, $0, $18, $1C
	dc.b $F8, $5, $0, $1C, $2C
	dc.b $F8, $5, $0, $42, $3C
DATA5E3YW3C9M1U_4: dc.b $9
	dc.b $F8, $5, $0, $3E, $C0
	dc.b $F8, $5, $0, $36, $D0
	dc.b $F8, $5, $0, $0, $E0
	dc.b $F8, $5, $0, $3A, $F0
	dc.b $F8, $5, $0, $22, $0
	dc.b $F8, $5, $0, $26, $10
	dc.b $F8, $1, $0, $20, $20
	dc.b $F8, $5, $0, $2E, $28
	dc.b $F8, $5, $0, $18, $38
DATA5E3YW3C9M1U_5: dc.b $9
	dc.b $F8, $5, $0, $8, $C0
	dc.b $F8, $5, $0, $26, $D0
	dc.b $F8, $5, $0, $32, $E0
	dc.b $F8, $5, $0, $8, $F0
	dc.b $F8, $5, $0, $22, $0
	dc.b $F8, $5, $0, $32, $30
	dc.b $F8, $5, $0, $3A, $40
	dc.b $F8, $5, $0, $22, $50
	dc.b $F8, $9, $0, $80, $18
DATA5E3YW3C9M1U_6: dc.b $4
	dc.b $F8, $5, $0, $4E, $E0
	dc.b $F8, $5, $0, $32, $F0
	dc.b $F8, $5, $0, $2E, $0
	dc.b $F8, $5, $0, $10, $10
DATA5E3YW3C9M1U_7: dc.b $C
	dc.b $FA, $1, $0, $18, $C0
	dc.b $F5, $1, $0, $1A, $CA
	dc.b $FF, $1, $0, $32, $CD
	dc.b $FD, $1, $0, $34, $D2
	dc.b $F6, $2, $0, $0, $E1
	dc.b $F8, $0, $0, $3, $E8
	dc.b $FB, $D, $0, $80, $EA
	dc.b $F2, $A, $0, $0, $FF
	dc.b $F6, $0, $0, $4A, $17
	dc.b $F5, $0, $0, $4B, $1C
	dc.b $FE, $0, $0, $4C, $20
	dc.b $FE, $0, $0, $4D, $1D
DATA5E3YW3C9M1U_8: dc.b $9
	dc.b $F7, $1, $0, $5A, $ED
	dc.b $F7, $1, $0, $5D, $F4
	dc.b $3, $1, $18, $5A, $F3
	dc.b $3, $1, $18, $5D, $EB
	dc.b $F5, $1, $0, $42, $F8
	dc.b $2, $1, $0, $68, $0
	dc.b $F8, $1, $0, $3A, $A
	dc.b $F8, $0, $0, $3C, $13
	dc.b $F0, $0, $0, $51, $0
DATA5E3YW3C9M1U_9: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $2, $0, $57, $C
DATA5E3YW3C9M1U_A: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $6, $0, $5A, $8
DATA5E3YW3C9M1U_B: dc.b $2
	dc.b $4, $C, $0, $53, $EC
	dc.b $F4, $6, $0, $60, $8
DATA5E3YW3C9M1U_C: dc.b $D
	dc.b $E4, $C, $0, $70, $F4
	dc.b $E4, $2, $0, $74, $14
	dc.b $EC, $4, $0, $77, $EC
	dc.b $F4, $5, $0, $79, $E4
	dc.b $14, $C, $18, $70, $EC
	dc.b $4, $2, $18, $74, $E4
	dc.b $C, $4, $18, $77, $4
	dc.b $FC, $5, $18, $79, $C
	dc.b $EC, $8, $0, $7D, $FC
	dc.b $F4, $C, $0, $7C, $F4
	dc.b $FC, $8, $0, $7C, $F4
	dc.b $4, $C, $0, $7C, $EC
	dc.b $C, $8, $0, $7C, $EC
DATA5E3YW3C9M1U_D: dc.b $5
	dc.b $F8, $5, $0, $14, $DC
	dc.b $F8, $1, $0, $20, $EC
	dc.b $F8, $5, $0, $2E, $F4
	dc.b $F8, $5, $0, $0, $4
	dc.b $F8, $5, $0, $26, $14
	even