; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Mar 16 2021 19:58:27 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAZLL58C9TQYQ:
	dc.w DATAZLL58C9TQYQ_0-DATAZLL58C9TQYQ
DATAZLL58C9TQYQ_0: dc.b $8
	dc.b $E9, $F, $0, $0, $D4
	dc.b $E1, $F, $0, $10, $F4
	dc.b $E1, $0, $0, $20, $14
	dc.b $9, $D, $0, $21, $D4
	dc.b $1, $B, $0, $29, $F4
	dc.b $F9, $2, $0, $35, $14
	dc.b $19, $0, $0, $38, $E4
	dc.b $21, $1, $0, $39, $F4
	even