//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1ObjectDefinitions.SLZ
{
    using SonicRetro.SonLVL.API;
    
    
    public class Elevator
    {
        
        public static object GetDelay(SonicRetro.SonLVL.API.ObjectEntry _obj)
        {
            SonicRetro.SonLVL.API.S1.S1ObjectEntry obj = ((SonicRetro.SonLVL.API.S1.S1ObjectEntry)(_obj));
return obj.SubType & 0x7F;
        }
        
        public static void SetDelay(SonicRetro.SonLVL.API.ObjectEntry _obj, object _val)
        {
            SonicRetro.SonLVL.API.S1.S1ObjectEntry obj = ((SonicRetro.SonLVL.API.S1.S1ObjectEntry)(_obj));
            int value = ((int)(_val));
obj.SubType = (byte)((obj.SubType & ~0x7F) | System.Math.Min(0x7F, value));
        }
    }
}
